(function() {
  "use strict";

  document.getElementById("booksBtn").addEventListener("click", function() {
    document.getElementById("booksSection").scrollIntoView({ behavior: "smooth" });
  });

  // ===================== READER SYSTEM =====================
  var books = {
    underground: {
      title: "Notes from Underground",
      cover: "Assets/Notes from Underground cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: The Underground Man", text: "<p>The narrator introduces himself as a sick, spiteful man — a retired civil servant living alone in a dark corner of St. Petersburg. He is forty years old and has been living underground for twenty years.</p><p>He tells us immediately that he is contradictory. He is intelligent enough to see the absurdity of his situation but too paralyzed to change it. His consciousness is both his greatest gift and his deepest curse.</p><p>The Underground Man represents a new type of character in literature: the anti-hero who is painfully self-aware yet unable to act. He is the first modern voice of alienation, speaking from the margins of a society he both despises and desperately wants to join.</p>" },
        { title: "Chapter 2: The Crystal Palace", text: "<p>The Underground Man attacks the rational utopians of his day — those who believe that science and reason can create a perfect society. He mocks the Crystal Palace, the symbol of progress and rational planning.</p><p>Human beings, he argues, do not want a perfect world. They want freedom — even the freedom to act against their own interests. A person will sometimes choose suffering over happiness just to prove that they are not a piano key being played by the laws of nature.</p><p>This is Dostoevsky's great insight: rationality alone cannot account for human behavior. People are irrational, contradictory, and perverse. Any system that ignores this will fail, no matter how logically perfect it appears.</p>" },
        { title: "Chapter 3: Two Times Two", text: "<p>The Underground Man declares that two times two equals four is not life but the beginning of death. Certainty is the enemy of freedom. If everything can be calculated and predicted, then human beings are nothing more than machines.</p><p>He would rather live in chaos than in a perfectly ordered world. He would rather suffer freely than be happy under compulsion. The ability to choose — even to choose badly — is what makes us human.</p><p>This chapter is a philosophical bombshell. Dostoevsky anticipates existentialism by decades, arguing that freedom is more fundamental than reason, and that the human will cannot be reduced to mathematical formulas.</p>" },
        { title: "Chapter 4: The Man of Action", text: "<p>The Underground Man envies the man of action — the simple, direct person who sees an obstacle and charges at it. Such a person does not overthink, does not doubt, does not paralyze themselves with analysis.</p><p>But the Underground Man cannot be a man of action because he sees too many sides of every question. Every time he tries to act, his consciousness intervenes, showing him the futility and absurdity of his intentions.</p><p>This paralysis of consciousness is the central problem of the modern intellectual. The more we understand, the less we can do. Knowledge becomes a prison rather than a liberation.</p>" },
        { title: "Chapter 5: Spite and Suffering", text: "<p>The Underground Man confesses that he sometimes enjoys his own suffering. There is a perverse pleasure in toothache, in humiliation, in self-destruction. This enjoyment of pain is not masochism but a form of rebellion against a rational universe.</p><p>If the world is governed by reason, then suffering should be avoided. But the Underground Man chooses suffering precisely because it is irrational. It proves that he is free, that he is not a cog in a machine.</p><p>Dostoevsky reveals the dark side of human freedom. We are capable not only of choosing good but of choosing evil, not only of seeking pleasure but of seeking pain. This capacity for self-destruction is inseparable from our capacity for freedom.</p>" },
        { title: "Chapter 6: The Dinner Party", text: "<p>The narrative shifts to a story from the Underground Man's past. He forces himself into a farewell dinner for a former schoolmate named Zverkov — a handsome, successful officer whom he secretly envies and despises.</p><p>The dinner is a disaster. The Underground Man arrives early, drinks too much, and delivers insulting speeches. His companions ignore him or mock him. He is humiliated but cannot bring himself to leave.</p><p>This scene is painfully realistic. Dostoevsky captures the agony of social awkwardness — the desperate desire to belong combined with the inability to connect. The Underground Man wants to be accepted but sabotages every opportunity.</p>" },
        { title: "Chapter 7: The Pursuit", text: "<p>After the dinner, the Underground Man follows his companions to a brothel, not out of desire but out of a compulsive need to confront Zverkov and demand satisfaction. He rehearses speeches in the carriage, imagining dramatic confrontations.</p><p>But when he arrives, his companions have already disappeared into private rooms. He is left alone, humiliated once again. His grand gestures collapse into farce. The gap between his fantasies and reality is unbridgeable.</p><p>This pattern — grandiose imagination followed by pathetic reality — defines the Underground Man's life. He lives in his head, constructing elaborate scenarios that never survive contact with the actual world.</p>" },
        { title: "Chapter 8: Liza", text: "<p>The Underground Man encounters Liza, a young woman working in the brothel. In a moment of unexpected eloquence, he paints a vivid picture of her future — disease, degradation, and an unmarked grave. He speaks with genuine passion and insight.</p><p>Liza is moved to tears. For a brief moment, the Underground Man transcends his selfishness and connects with another human being. He gives her his address and invites her to visit him, promising to help her escape her life.</p><p>But even as he speaks, he is aware of his own performance. Is he genuinely moved by compassion, or is he enjoying the power of his words? The Underground Man can never be sure of his own motives, and neither can the reader.</p>" },
        { title: "Chapter 9: Liza's Visit", text: "<p>When Liza arrives at his apartment, the Underground Man is horrified. His room is shabby, his servant is insolent, and he is wearing a dirty dressing gown. The noble savior she expected does not exist.</p><p>Instead of helping her, he breaks down in tears and confesses that his speech at the brothel was a performance — he was playing a role, enjoying his own eloquence. He tells her he was using her to feel powerful.</p><p>Liza responds not with anger but with compassion. She sees through his cruelty to the suffering beneath it. She embraces him, and for a moment, genuine human connection seems possible.</p>" },
        { title: "Chapter 10: The Final Humiliation", text: "<p>But the Underground Man cannot accept love. When Liza shows him compassion, he responds with cruelty. He presses money into her hand — payment for her services — deliberately reducing their connection to a commercial transaction.</p><p>Liza leaves without taking the money. The Underground Man runs after her but she is gone. He returns to his room and finds the crumpled bills on the table. He has destroyed the one genuine human connection he has ever made.</p><p>The novella ends with the Underground Man still writing, still analyzing, still trapped in his consciousness. He tells us that he will stop writing — but we know he won't. The underground is not a place but a state of mind, and there is no escape from the prison of self-awareness.</p>" }
      ]
    },
    crimeandpunishment: {
      title: "Crime and Punishment",
      cover: "Assets/Crime and punishment cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: Raskolnikov's Theory", text: "<p>Rodion Raskolnikov, a destitute former student in St. Petersburg, has developed a theory that divides humanity into two categories: ordinary people who must obey the law, and extraordinary people who have the right to transgress it for a higher purpose.</p><p>Napoleon, he reasons, killed thousands and was celebrated as a hero. If a great man can step over moral boundaries for the sake of progress, why can't Raskolnikov? He is intelligent, talented, and destined for greatness — or so he believes.</p><p>This theory is not merely academic. Raskolnikov plans to test it by murdering Alyona Ivanovna, a cruel old pawnbroker. He tells himself that her death will benefit humanity — he will use her money to help the poor and launch his career.</p>" },
        { title: "Chapter 2: The Murder", text: "<p>Raskolnikov commits the murder with an axe, striking the old woman on the skull. But the crime does not go as planned. Her half-sister Lizaveta arrives unexpectedly, and Raskolnikov kills her too — an innocent woman who never harmed anyone.</p><p>The second murder shatters Raskolnikov's theory. He was supposed to be an extraordinary man committing a calculated act for the greater good. Instead, he is a panicked killer who has murdered an innocent bystander.</p><p>Raskolnikov barely escapes detection. He stumbles home in a daze, hides the stolen goods without even counting them, and falls into a fever that lasts for days. The crime that was supposed to prove his greatness has instead revealed his weakness.</p>" },
        { title: "Chapter 3: The Aftermath", text: "<p>Raskolnikov wakes from his fever to find that the world has changed — or rather, that he has changed. He is paranoid, irritable, and unable to connect with the people who love him. His mother and sister arrive in Petersburg, but he can barely speak to them.</p><p>He wanders the streets in a fog, alternating between terror that he will be caught and a strange desire to confess. He returns to the scene of the crime, rings the doorbell, and asks the painters about the blood — behavior that is both reckless and compulsive.</p><p>The psychological realism of these scenes is extraordinary. Dostoevsky shows how guilt transforms a person from the inside out, destroying their ability to function long before any external punishment arrives.</p>" },
        { title: "Chapter 4: Porfiry Petrovich", text: "<p>The investigating magistrate Porfiry Petrovich suspects Raskolnikov from the beginning. But he has no evidence — only psychological intuition. He engages Raskolnikov in a series of cat-and-mouse conversations, probing his theory and watching his reactions.</p><p>Porfiry is one of literature's great detectives. He does not rely on clues or witnesses but on his understanding of human nature. He knows that a guilty conscience will eventually betray itself — he just needs to apply the right pressure.</p><p>Their conversations are intellectual duels. Raskolnikov tries to maintain his composure while Porfiry circles closer and closer to the truth. The tension is unbearable because both men know what is at stake.</p>" },
        { title: "Chapter 5: Sonya Marmeladova", text: "<p>Sonya is the daughter of a ruined drunkard who has been forced into prostitution to feed her family. Despite her degradation, she maintains a pure and compassionate spirit. She is Raskolnikov's moral opposite — she suffers for others while he makes others suffer.</p><p>Raskolnikov is drawn to Sonya because she represents everything his theory denies: the power of love, the reality of sin, and the possibility of redemption. She reads him the story of Lazarus from the Bible — the dead man raised to life.</p><p>Sonya does not judge Raskolnikov. She weeps for him. She sees his crime not as proof of his superiority but as evidence of his suffering. Her compassion begins to crack the armor of his intellectual pride.</p>" },
        { title: "Chapter 6: The Confession", text: "<p>Raskolnikov finally confesses to Sonya. He tells her everything — the theory, the murder, the second killing. But even in confession, he cannot fully accept his guilt. He insists that he killed not for money but to test whether he was an extraordinary man.</p><p>The terrible truth emerges: he failed the test. An extraordinary man would not feel guilt. An extraordinary man would not be tormented by nightmares. Raskolnikov's suffering proves that he is ordinary — that he is, in his own terms, a louse.</p><p>Sonya tells him he must go to the crossroads, bow down, kiss the earth, and confess to the world. Only through suffering and repentance can he be reborn. Raskolnikov resists, but her words plant a seed that will eventually grow.</p>" },
        { title: "Chapter 7: Svidrigailov", text: "<p>Svidrigailov is Raskolnikov's dark double — a man who has crossed every moral boundary without remorse. He is suspected of murder, accused of abuse, and haunted by the ghosts of his victims. Yet he feels no guilt.</p><p>Svidrigailov represents what Raskolnikov's theory looks like in practice. If there are no moral limits, then everything is permitted — including the most terrible cruelties. Svidrigailov is the logical endpoint of Raskolnikov's philosophy.</p><p>But even Svidrigailov cannot escape his conscience entirely. He is plagued by nightmares and a growing sense of emptiness. His final act — suicide — proves that a life without moral boundaries is ultimately unbearable.</p>" },
        { title: "Chapter 8: The Surrender", text: "<p>Raskolnikov goes to the police station and confesses. The scene is anticlimactic — no dramatic confrontation, no eloquent speech. He simply tells the clerk what he has done. The great theory ends not with a bang but with a whisper.</p><p>Before confessing, he goes to the crossroads as Sonya instructed. He kneels and kisses the earth. A bystander mocks him, thinking he is drunk. But for Raskolnikov, this moment of humiliation is the beginning of redemption.</p><p>Sonya follows him to Siberia. She does not abandon him, even though he has committed a terrible crime. Her faithfulness is the novel's answer to Raskolnikov's theory: love is stronger than logic, and compassion is more powerful than intellect.</p>" },
        { title: "Chapter 9: Siberia", text: "<p>In the prison camp, Raskolnikov is initially unchanged. He does not repent. He considers his crime a mistake in execution, not in principle. The other prisoners dislike him — they sense his pride and contempt.</p><p>But Sonya visits him faithfully. She brings him food, news, and quiet companionship. The other prisoners love her. They call her 'little mother' and treat her with reverence. Her goodness is visible to everyone except Raskolnikov.</p><p>Slowly, imperceptibly, Raskolnikov begins to change. He does not have a dramatic conversion but a gradual thawing of the heart. Sonya's patient love accomplishes what no argument could — it breaks through his intellectual defenses.</p>" },
        { title: "Chapter 10: Resurrection", text: "<p>The novel's final scene is one of the most powerful in all literature. Raskolnikov falls ill and has a dream of a plague that infects people with the conviction that they alone possess the truth. The infected destroy each other in their certainty.</p><p>When he recovers, something has changed. He sees Sonya and is overwhelmed with emotion. He falls at her feet and weeps. She understands — love has raised them from the dead, just as Lazarus was raised.</p><p>Dostoevsky does not show us Raskolnikov's full redemption — that, he says, would be another story. But the direction is clear. Through suffering, confession, and love, a man who tried to place himself above morality has been brought back to humanity. The crime demanded punishment, but the punishment opened the door to resurrection.</p>" }
      ]
    },
    karamazov: {
      title: "The Brothers Karamazov",
      cover: "Assets/The Brothers Karamazov cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: The Karamazov Family", text: "<p>Fyodor Pavlovich Karamazov is a buffoon, a drunkard, and a terrible father. He has three legitimate sons — Dmitri, Ivan, and Alyosha — and possibly a fourth, the illegitimate Smerdyakov. Each son represents a different response to their father's corruption.</p><p>Dmitri is passionate and impulsive, driven by desire and honor. Ivan is intellectual and tormented, consumed by philosophical questions about God and morality. Alyosha is gentle and spiritual, a novice in the local monastery.</p><p>The family gathers at the monastery of the Elder Zosima, ostensibly to resolve a financial dispute between Dmitri and his father. But the meeting descends into chaos, revealing the deep hatred and dysfunction that will drive the novel's tragedy.</p>" },
        { title: "Chapter 2: The Elder Zosima", text: "<p>Father Zosima is the spiritual heart of the novel. He is a monk of extraordinary wisdom and compassion who can see into people's souls. When the Karamazov family visits, Zosima bows to the ground before Dmitri — sensing the great suffering that awaits him.</p><p>Zosima teaches that every person is responsible for everyone else's sins. We are all connected in a web of mutual responsibility. To judge another is to judge yourself. To forgive another is to free yourself.</p><p>His teachings stand in direct opposition to Ivan's philosophy. Where Ivan sees a world of meaningless suffering, Zosima sees a world of sacred interconnection. Where Ivan demands justice, Zosima offers love.</p>" },
        { title: "Chapter 3: The Grand Inquisitor", text: "<p>Ivan tells Alyosha a poem he has composed: The Grand Inquisitor. In it, Christ returns to earth during the Spanish Inquisition. The Grand Inquisitor arrests him and explains why the Church has corrected his work.</p><p>Christ offered humanity freedom, but freedom is a burden most people cannot bear. The Church has taken away their freedom and given them bread, miracles, and authority instead. The people are happier as slaves than they ever were as free beings.</p><p>This is the most famous chapter in all of Dostoevsky. It poses the ultimate question: is freedom worth the suffering it causes? The Grand Inquisitor says no. Christ says nothing — he simply kisses the old man on his bloodless lips.</p>" },
        { title: "Chapter 4: Ivan's Rebellion", text: "<p>Before telling the Grand Inquisitor story, Ivan presents his case against God. He does not deny God's existence — he rejects God's world. Specifically, he cannot accept a universe in which innocent children suffer.</p><p>Ivan describes real cases of children being tortured and killed. He asks Alyosha: if you could create a perfect world but it required the torture of one innocent child, would you accept it? Alyosha whispers: no.</p><p>Ivan's rebellion is not atheism but something more radical — it is a moral rejection of creation itself. Even if God exists, even if there is a higher harmony that justifies all suffering, Ivan returns his ticket. He will not accept paradise at the price of a child's tears.</p>" },
        { title: "Chapter 5: Dmitri's Passion", text: "<p>Dmitri is consumed by his love for Grushenka, a beautiful and manipulative woman who is also pursued by his father. The rivalry between father and son over the same woman creates an explosive situation.</p><p>Dmitri is also tormented by a debt of honor. He has spent three thousand rubles that were entrusted to him by his fiancée Katerina. He desperately needs money to repay her and run away with Grushenka.</p><p>On the night of the murder, Dmitri goes to his father's house with a brass pestle, intending to demand his inheritance. He finds the old man alone, leaning out the window, calling for Grushenka. Dmitri raises the pestle — but does he strike?</p>" },
        { title: "Chapter 6: The Murder", text: "<p>Fyodor Pavlovich is found murdered in his house. Dmitri is the obvious suspect — he had motive, opportunity, and was seen running from the scene with blood on his hands. But the blood came from striking a servant, not from killing his father.</p><p>The real murderer is Smerdyakov, the illegitimate son and servant, who was inspired by Ivan's philosophy that 'if God does not exist, everything is permitted.' Smerdyakov took Ivan's ideas to their logical conclusion.</p><p>This is Dostoevsky's most devastating argument against atheistic rationalism. Ideas have consequences. When a philosopher declares that morality has no foundation, someone will eventually act on that declaration.</p>" },
        { title: "Chapter 7: The Trial", text: "<p>Dmitri is put on trial for his father's murder. The evidence against him is overwhelming but circumstantial. The prosecution builds a compelling case based on motive, opportunity, and Dmitri's violent temperament.</p><p>The defense argues that there is no direct evidence — no witness saw Dmitri commit the murder. But the jury is swayed by the prosecution's narrative. Dmitri's passionate nature, his public threats against his father, and his desperate need for money all point to guilt.</p><p>The trial becomes a spectacle that divides the town. Women sympathize with Dmitri; men condemn him. The verdict will depend not on evidence but on the jury's judgment of Dmitri's character.</p>" },
        { title: "Chapter 8: Smerdyakov's Confession", text: "<p>Before the trial concludes, Smerdyakov confesses to Ivan in a series of private meetings. He reveals that he murdered Fyodor Pavlovich and stole the money. He did it, he says, because Ivan taught him that everything is permitted.</p><p>Ivan is horrified. He never intended his philosophy to inspire murder. But Smerdyakov shows him the logical connection: if there is no God, there is no morality. If there is no morality, there is no reason not to kill. Ivan's ideas led directly to his father's death.</p><p>Smerdyakov hangs himself, taking the only evidence of his guilt with him. Ivan is left with the knowledge that his philosophy killed his father — a burden that drives him to madness.</p>" },
        { title: "Chapter 9: Alyosha's Faith", text: "<p>Throughout the novel, Alyosha represents the possibility of faith in a world of suffering. He does not have answers to Ivan's arguments — he simply lives a life of love and compassion that serves as its own answer.</p><p>After Zosima's death, Alyosha experiences a crisis of faith. The elder's body decomposes quickly, which the monks interpret as a sign of spiritual failure. Alyosha is shaken — but then he has a vision of Zosima at the wedding feast of Cana.</p><p>This vision restores Alyosha's faith. He goes outside, falls to the earth, and kisses it, weeping with joy. He rises a different person — stronger, more certain, ready to carry Zosima's message of love into the world.</p>" },
        { title: "Chapter 10: The Boys and the Future", text: "<p>The novel ends not with the Karamazov brothers but with a group of boys gathered around the grave of their friend Ilyusha, who has died of illness. Alyosha speaks to them about the power of good memories.</p><p>He tells them that one good memory from childhood can save a person's entire life. Even if they grow up to be cruel or cynical, the memory of this moment — standing together in love and grief — may pull them back from the edge.</p><p>The Brothers Karamazov ends with the boys shouting 'Hurrah for Karamazov!' — not for the corrupt father but for Alyosha, who represents hope. Dostoevsky's final message is that love, not logic, is the answer to the problem of evil. Faith is not a philosophical argument but a way of living that transforms the world one person at a time.</p>" }
      ]
    }
  };

  var currentBook = null, currentPage = 0;

  function openBook(k) { currentBook = books[k]; if (!currentBook) return; currentPage = 0; document.getElementById("readerOverlay").classList.add("active"); document.body.style.overflow = "hidden"; renderPage(); }
  function closeBook() { document.getElementById("readerOverlay").classList.remove("active"); document.body.style.overflow = ""; currentBook = null; }
  function renderPage() {
    if (!currentBook) return;
    var ch = currentBook.chapters[currentPage], ci = document.getElementById("readerCoverImg"), ce = document.getElementById("readerChapter"), ti = document.getElementById("chapterTitle"), te = document.getElementById("chapterText"), ind = document.getElementById("readerIndicator"), rt = document.getElementById("readerTitle"), pb = document.getElementById("readerPrev"), nb = document.getElementById("readerNext");
    if (ch.type === "cover") { ci.style.display="block"; ci.src=currentBook.cover; ce.classList.remove("visible"); rt.textContent=currentBook.title; }
    else { ci.style.display="none"; ce.classList.add("visible"); ti.textContent=ch.title; te.innerHTML=ch.text; rt.textContent=ch.title; ce.scrollTop=0; }
    ind.textContent=(currentPage+1)+" / "+currentBook.chapters.length; pb.disabled=currentPage===0; nb.disabled=currentPage===currentBook.chapters.length-1;
  }

  document.querySelectorAll(".book-read-btn").forEach(function(b){b.addEventListener("click",function(){openBook(b.dataset.book);});});
  document.getElementById("readerBackBtn").addEventListener("click",closeBook);
  document.getElementById("readerPrev").addEventListener("click",function(){if(currentBook&&currentPage>0){currentPage--;renderPage();}});
  document.getElementById("readerNext").addEventListener("click",function(){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}});
  document.addEventListener("keydown",function(e){if(!document.getElementById("readerOverlay").classList.contains("active"))return;if(e.key==="ArrowRight"){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}}else if(e.key==="ArrowLeft"){if(currentBook&&currentPage>0){currentPage--;renderPage();}}else if(e.key==="Escape"){closeBook();}});
  var scrollCD=false;document.getElementById("readerOverlay").addEventListener("wheel",function(e){if(!currentBook||scrollCD)return;var ce=document.getElementById("readerChapter");if(currentPage===0||!ce.classList.contains("visible")){e.preventDefault();scrollCD=true;if(e.deltaY>0&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}else if(e.deltaY<0&&currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);return;}var aT=ce.scrollTop<=0,aB=ce.scrollTop+ce.clientHeight>=ce.scrollHeight-5;if(aB&&e.deltaY>0){e.preventDefault();scrollCD=true;if(currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}setTimeout(function(){scrollCD=false;},200);}else if(aT&&e.deltaY<0){e.preventDefault();scrollCD=true;if(currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);}},{passive:false});

  // ===================== 3D MODEL =====================
  var container = document.getElementById("modelContainer");
  var w = container.clientWidth, h = container.clientHeight;
  var scene = new THREE.Scene();
  var camera = new THREE.PerspectiveCamera(45, w/h, 0.01, 100);
  camera.position.set(0, 1, 3);
  var renderer = new THREE.WebGLRenderer({ antialias:true, alpha:true });
  renderer.setClearColor(0x000000, 0);
  renderer.setSize(w, h);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  container.appendChild(renderer.domElement);
  var controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping=true; controls.dampingFactor=0.05; controls.autoRotate=true; controls.autoRotateSpeed=2; controls.enableZoom=false; controls.target.set(0,0.8,0);
  scene.add(new THREE.AmbientLight(0xffffff,0.6));
  var dl=new THREE.DirectionalLight(0xffffff,1.5); dl.position.set(2,4,3); scene.add(dl);
  var fl=new THREE.DirectionalLight(0xffeedd,0.5); fl.position.set(-2,2,-1); scene.add(fl);
  scene.add(new THREE.HemisphereLight(0xffeeb1,0x080820,0.3));
  var loader=new THREE.GLTFLoader();
  loader.load("Assets/Fyodor Dostoevsky.glb",function(g){var m=g.scene;var b=new THREE.Box3().setFromObject(m);var c=b.getCenter(new THREE.Vector3());var s=b.getSize(new THREE.Vector3());var mx=Math.max(s.x,s.y,s.z);var sc=2/mx;m.scale.setScalar(sc);m.position.sub(c.multiplyScalar(sc));m.position.y+=0.5;scene.add(m);controls.target.set(0,m.position.y+(s.y*sc)/2,0);},undefined,function(e){console.warn("Failed to load model:",e);});
  function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();
  window.addEventListener("resize",function(){var w2=container.clientWidth,h2=container.clientHeight;camera.aspect=w2/h2;camera.updateProjectionMatrix();renderer.setSize(w2,h2);});
})();
