(function() {
  "use strict";

  document.getElementById("booksBtn").addEventListener("click", function() {
    document.getElementById("booksSection").scrollIntoView({ behavior: "smooth" });
  });

  // ===================== READER SYSTEM =====================
  var books = {
    enchiridion: {
      title: "Enchiridion",
      cover: "Assets/Enchridion cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: What Is in Our Power", text: "<p>Epictetus opens with the most fundamental distinction in Stoic philosophy: some things are within our power and some are not. Our opinions, desires, aversions, and actions are within our power. Our bodies, possessions, reputations, and positions are not.</p><p>If we confuse these two categories, we will be frustrated, disturbed, and blame both gods and men. We will feel like victims of circumstance, tossed about by forces beyond our control.</p><p>But if we focus only on what is truly ours — our judgments and choices — we become invincible. No one can compel us to think or choose against our will. This is the foundation of Stoic freedom.</p>" },
        { title: "Chapter 2: Desire and Aversion", text: "<p>Epictetus warns against desiring things outside our control. If you desire health, wealth, or the love of others, you set yourself up for disappointment. These things depend on fortune, not on your will.</p><p>Instead, desire only what is within your power: virtue, wisdom, and right action. If you desire only what you can achieve through your own effort, you will never be frustrated.</p><p>Similarly, be averse only to things within your control that are contrary to nature — vice, ignorance, and moral failure. Do not be averse to illness, poverty, or death, for these are not evils but indifferent things.</p>" },
        { title: "Chapter 3: Impressions and Judgment", text: "<p>When a disturbing impression strikes your mind, do not be carried away by it. Say to yourself: you are just an impression, not the thing you represent. Then examine it using the principles you have learned.</p><p>Most of our suffering comes not from events themselves but from our judgments about them. Death is not terrible — the judgment that death is terrible is what terrifies us. If we can change our judgments, we can change our experience.</p><p>This practice of examining impressions is the core discipline of Stoicism. It requires constant vigilance and training, but it leads to a tranquility that external circumstances cannot disturb.</p>" },
        { title: "Chapter 4: Preparing for Adversity", text: "<p>Before undertaking any action, consider what is involved. If you go to the public baths, remind yourself that people there will splash, push, and steal. If you prepare for this in advance, you will not be disturbed when it happens.</p><p>Apply this principle to everything. Before leaving the house, tell yourself: I may encounter rude people, ungrateful people, and liars. But I will not be harmed by them unless I choose to be disturbed.</p><p>This is not pessimism but realism. By anticipating difficulties, we remove their power to surprise and upset us. We maintain our equanimity because we have already accepted what may come.</p>" },
        { title: "Chapter 5: The Role of Others", text: "<p>Remember that you are an actor in a play whose character has been assigned by the director. If your role is short, play it well. If it is long, play it well. Whether you play a beggar, a king, or a cripple, your job is to play the role excellently.</p><p>Do not wish that events happen as you want them to. Wish that they happen as they do happen, and your life will go smoothly. This is not passive resignation but active acceptance of reality.</p><p>When someone insults you, remember that it is not the insult that hurts but your opinion of it. When you are tempted to anger, remind yourself that giving in to anger harms you more than the person who provoked it.</p>" },
        { title: "Chapter 6: Attachment and Loss", text: "<p>When you kiss your child or spouse, remind yourself that you are kissing a mortal being. Then if they die, you will not be devastated. This sounds harsh, but Epictetus is not asking us to love less — he is asking us to love wisely.</p><p>Everything we have is on loan from fortune. Our possessions, our relationships, even our bodies are temporary. If we remember this, we will cherish what we have without clinging to it desperately.</p><p>The person who understands impermanence loves more deeply, not less. They appreciate each moment because they know it will not last. Attachment breeds anxiety; acceptance breeds gratitude.</p>" },
        { title: "Chapter 7: Living with Others", text: "<p>Do not say that you have lost something — say that you have returned it. Your child has died? They have been returned. Your property has been taken? It has been returned. The giver has taken it back.</p><p>In your relationships, focus on your own duties rather than others' faults. A good brother does not complain about his sibling but fulfills his own role. A good citizen does not criticize the government but contributes what he can.</p><p>When others behave badly, remember that they act from ignorance, not malice. If they truly understood what was good, they would choose it. Pity the ignorant rather than hating them.</p>" },
        { title: "Chapter 8: The Discipline of Action", text: "<p>In every action, ask yourself: what would a wise person do? Before speaking, consider whether your words are necessary, true, and kind. Before acting, consider whether your action aligns with virtue.</p><p>Do not boast about your philosophical progress. Do not lecture others about how they should live. Instead, demonstrate your principles through your actions. A sheep does not vomit up grass to show the shepherd how much it has eaten — it digests the grass and produces wool.</p><p>The true philosopher is known not by their words but by their character. They are patient in adversity, moderate in prosperity, and kind to all. Their philosophy is visible in how they live, not in what they say.</p>" },
        { title: "Chapter 9: Freedom and Slavery", text: "<p>No one can take your freedom unless you give it away. The person who fears death is a slave to death. The person who craves wealth is a slave to wealth. True freedom comes from wanting only what is within your power.</p><p>Epictetus, who was born a slave, understood freedom better than most free men. He knew that physical chains are nothing compared to the chains of desire, fear, and false opinion that bind the soul.</p><p>The free person is not the one who has no master but the one who has mastered themselves. They cannot be compelled, bribed, or threatened into abandoning their principles. This inner freedom is the goal of Stoic practice.</p>" },
        { title: "Chapter 10: The Stoic Life", text: "<p>Epictetus concludes with practical advice for daily life. Eat simply, exercise moderately, and speak little. Avoid gossip, complaints, and excessive entertainment. These habits strengthen the soul just as physical training strengthens the body.</p><p>When you fail — and you will fail — do not despair. Simply return to your principles and try again. Progress in philosophy is not measured by perfection but by the direction of your effort.</p><p>The Enchiridion ends with a reminder: keep these principles at hand, meditate on them daily, and practice them in every situation. Philosophy is not a subject to be studied but a way of life to be lived. The goal is not knowledge but transformation.</p>" }
      ]
    },
    discourses: {
      title: "Discourses",
      cover: "Assets/Discourses cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: On Freedom", text: "<p>Epictetus begins the Discourses with a powerful meditation on freedom. True freedom, he argues, is not political liberty but the ability to live according to one's own rational nature without being enslaved by passions or external circumstances.</p><p>A person in chains who maintains their inner composure is freer than a tyrant consumed by fear and desire. The emperor who cannot control his anger is a slave; the prisoner who accepts his fate with equanimity is free.</p><p>Freedom requires constant practice. We must train ourselves to distinguish between what depends on us and what does not, and to focus our energy exclusively on the former. This discipline is the essence of the philosophical life.</p>" },
        { title: "Chapter 2: How to Deal with Difficult People", text: "<p>When someone treats you badly, remember that they are acting from their own understanding of what is good. They are not evil — they are mistaken. If they truly understood what was beneficial, they would act differently.</p><p>Epictetus uses the analogy of a blind person stepping on your foot. You would not be angry at them because you understand they cannot see. Similarly, the person who wrongs you is blind to the truth. They deserve compassion, not anger.</p><p>This does not mean we should tolerate injustice passively. We should correct others when possible, but without hatred or resentment. Our goal is to maintain our own virtue regardless of how others behave.</p>" },
        { title: "Chapter 3: On Training and Habit", text: "<p>Philosophy is not merely theoretical — it is a practice that must be trained daily, like athletics. Every impression that strikes the mind is an opportunity to exercise judgment. Every interaction is a chance to practice virtue.</p><p>Epictetus compares the philosopher to a wrestler. A wrestler does not learn their art by reading about it but by grappling with opponents. Similarly, the philosopher learns by engaging with the challenges of daily life.</p><p>Bad habits are broken by replacing them with good ones. If you are prone to anger, practice patience at every opportunity. If you are prone to fear, deliberately face what frightens you. Repetition transforms character.</p>" },
        { title: "Chapter 4: On Providence", text: "<p>Epictetus argues that the universe is governed by a rational providence. Everything that happens serves a purpose, even if we cannot always see it. Difficulties are not punishments but opportunities for growth.</p><p>Just as a wrestling coach assigns tough opponents to develop an athlete's strength, providence assigns challenges to develop our character. Illness, poverty, and loss are the training weights of the soul.</p><p>This does not mean we should seek suffering. But when it comes, we should recognize it as part of our education. The person who complains about their circumstances is like a student who complains about their homework — they miss the point of the exercise.</p>" },
        { title: "Chapter 5: On Roles and Relationships", text: "<p>Every person occupies multiple roles: parent, child, citizen, friend, human being. Each role carries specific duties. The philosopher fulfills all their roles with excellence, not just the ones they find convenient.</p><p>A father's duty is to care for his children. A citizen's duty is to contribute to the common good. A human being's duty is to exercise reason and virtue. These duties are not burdens but expressions of our nature.</p><p>When roles conflict, we must use reason to determine which duty takes priority. But we should never abandon a role entirely. The person who neglects their family for philosophy has misunderstood philosophy itself.</p>" },
        { title: "Chapter 6: On Desire and Contentment", text: "<p>Most people are miserable because they desire what they do not have and fear losing what they do. This creates an endless cycle of anxiety and dissatisfaction. The Stoic breaks this cycle by desiring only virtue.</p><p>Contentment does not mean having everything you want — it means wanting only what you have. The rich person who craves more is poorer than the poor person who is satisfied. Wealth is measured not by possessions but by the absence of want.</p><p>Epictetus teaches his students to practice voluntary simplicity. Eat plain food, wear simple clothes, sleep on a hard bed. Not as punishment, but as training. The person who can be happy with little can be happy anywhere.</p>" },
        { title: "Chapter 7: On Courage and Death", text: "<p>Fear of death is the root of all cowardice. The person who fears death can be controlled by anyone who threatens it. But the person who has accepted death is beyond all threats.</p><p>Epictetus reminds his students that death is natural and inevitable. It is not an evil but a return to the elements from which we came. The fear of death is based on ignorance, not wisdom.</p><p>True courage is not the absence of fear but the judgment that something else is more important than fear. The soldier who fights despite fear, the philosopher who speaks truth despite danger — these are the truly courageous.</p>" },
        { title: "Chapter 8: On Education and Progress", text: "<p>The beginning of philosophy is the recognition of one's own ignorance. The person who thinks they already know everything cannot learn. Only the person who admits their confusion is ready for wisdom.</p><p>Progress in philosophy is measured not by how much you know but by how you live. The person who can recite every Stoic principle but loses their temper at dinner has made no progress at all.</p><p>Epictetus warns against the trap of intellectual vanity. Some students collect philosophical arguments like trophies, showing them off in conversation. But philosophy is medicine for the soul, not decoration for the mind.</p>" },
        { title: "Chapter 9: On Consistency", text: "<p>The greatest challenge in philosophy is consistency. It is easy to be virtuous when things go well. The test comes when we face adversity, insult, or temptation. Can we maintain our principles under pressure?</p><p>Epictetus observes that many people are philosophers in the classroom but slaves in the marketplace. They discuss freedom eloquently but panic at the first sign of trouble. Theory without practice is worthless.</p><p>The goal is to become the same person in every situation — calm in crisis, humble in success, kind to enemies, honest with friends. This consistency of character is the mark of true philosophical achievement.</p>" },
        { title: "Chapter 10: On the Philosopher's Mission", text: "<p>The philosopher has a mission in the world: to serve as an example of how a human being should live. Not through preaching or lecturing, but through the quiet demonstration of virtue in action.</p><p>Epictetus compares the philosopher to a scout sent ahead by an army. The scout's job is to explore the terrain and report back honestly. The philosopher explores the human condition and shows others what is possible.</p><p>The Discourses end with a call to action. Philosophy is not a retreat from the world but an engagement with it. The Stoic does not withdraw to a monastery — they live in the city, raise families, serve their communities, and face every challenge with courage, wisdom, and compassion.</p>" }
      ]
    }
  };

  var currentBook = null, currentPage = 0;

  function openBook(k) { currentBook = books[k]; if (!currentBook) return; currentPage = 0; document.getElementById("readerOverlay").classList.add("active"); document.body.style.overflow = "hidden"; renderPage(); }
  function closeBook() { document.getElementById("readerOverlay").classList.remove("active"); document.body.style.overflow = ""; currentBook = null; }
  function renderPage() {
    if (!currentBook) return;
    var ch = currentBook.chapters[currentPage], ci = document.getElementById("readerCoverImg"), ce = document.getElementById("readerChapter"), ti = document.getElementById("chapterTitle"), te = document.getElementById("chapterText"), ind = document.getElementById("readerIndicator"), rt = document.getElementById("readerTitle"), pb = document.getElementById("readerPrev"), nb = document.getElementById("readerNext");
    if (ch.type === "cover") { ci.style.display="block"; ci.src=currentBook.cover; ce.classList.remove("visible"); rt.textContent=currentBook.title; }
    else { ci.style.display="none"; ce.classList.add("visible"); ti.textContent=ch.title; te.innerHTML=ch.text; rt.textContent=ch.title; ce.scrollTop=0; }
    ind.textContent=(currentPage+1)+" / "+currentBook.chapters.length; pb.disabled=currentPage===0; nb.disabled=currentPage===currentBook.chapters.length-1;
  }

  document.querySelectorAll(".book-read-btn").forEach(function(b){b.addEventListener("click",function(){openBook(b.dataset.book);});});
  document.getElementById("readerBackBtn").addEventListener("click",closeBook);
  document.getElementById("readerPrev").addEventListener("click",function(){if(currentBook&&currentPage>0){currentPage--;renderPage();}});
  document.getElementById("readerNext").addEventListener("click",function(){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}});
  document.addEventListener("keydown",function(e){if(!document.getElementById("readerOverlay").classList.contains("active"))return;if(e.key==="ArrowRight"){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}}else if(e.key==="ArrowLeft"){if(currentBook&&currentPage>0){currentPage--;renderPage();}}else if(e.key==="Escape"){closeBook();}});
  var scrollCD=false;document.getElementById("readerOverlay").addEventListener("wheel",function(e){if(!currentBook||scrollCD)return;var ce=document.getElementById("readerChapter");if(currentPage===0||!ce.classList.contains("visible")){e.preventDefault();scrollCD=true;if(e.deltaY>0&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}else if(e.deltaY<0&&currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);return;}var aT=ce.scrollTop<=0,aB=ce.scrollTop+ce.clientHeight>=ce.scrollHeight-5;if(aB&&e.deltaY>0){e.preventDefault();scrollCD=true;if(currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}setTimeout(function(){scrollCD=false;},200);}else if(aT&&e.deltaY<0){e.preventDefault();scrollCD=true;if(currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);}},{passive:false});

  // ===================== 3D MODEL =====================
  var container = document.getElementById("modelContainer");
  var w = container.clientWidth, h = container.clientHeight;
  var scene = new THREE.Scene();
  var camera = new THREE.PerspectiveCamera(45, w/h, 0.01, 100);
  camera.position.set(0, 1, 3);
  var renderer = new THREE.WebGLRenderer({ antialias:true, alpha:true });
  renderer.setClearColor(0x000000, 0);
  renderer.setSize(w, h);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  container.appendChild(renderer.domElement);
  var controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping=true; controls.dampingFactor=0.05; controls.autoRotate=true; controls.autoRotateSpeed=2; controls.enableZoom=false; controls.target.set(0,0.8,0);
  scene.add(new THREE.AmbientLight(0xffffff,0.6));
  var dl=new THREE.DirectionalLight(0xffffff,1.5); dl.position.set(2,4,3); scene.add(dl);
  var fl=new THREE.DirectionalLight(0xffeedd,0.5); fl.position.set(-2,2,-1); scene.add(fl);
  scene.add(new THREE.HemisphereLight(0xffeeb1,0x080820,0.3));
  var loader=new THREE.GLTFLoader();
  loader.load("Assets/epectices.glb",function(g){var m=g.scene;var b=new THREE.Box3().setFromObject(m);var c=b.getCenter(new THREE.Vector3());var s=b.getSize(new THREE.Vector3());var mx=Math.max(s.x,s.y,s.z);var sc=2/mx;m.scale.setScalar(sc);m.position.sub(c.multiplyScalar(sc));m.position.y+=0.5;scene.add(m);controls.target.set(0,m.position.y+(s.y*sc)/2,0);},undefined,function(e){console.warn("Failed to load model:",e);});
  function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();
  window.addEventListener("resize",function(){var w2=container.clientWidth,h2=container.clientHeight;camera.aspect=w2/h2;camera.updateProjectionMatrix();renderer.setSize(w2,h2);});
})();
