(function() {
  "use strict";

  document.getElementById("booksBtn").addEventListener("click", function() {
    document.getElementById("booksSection").scrollIntoView({ behavior: "smooth" });
  });

  // ===================== READER SYSTEM =====================
  var books = {
    sapiens: {
      title: "Sapiens",
      cover: "Assets/Sapiens cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: The Cognitive Revolution", text: "<p>About 70,000 years ago, Homo sapiens underwent a dramatic transformation. Something changed in the wiring of our brains that gave us the ability to think in entirely new ways — to imagine things that do not exist, to gossip about absent people, and to create shared fictions.</p><p>This Cognitive Revolution was the most important event in human history. It allowed sapiens to cooperate in large numbers by believing in common myths — gods, nations, money, and human rights. No other animal can do this.</p><p>Before the Cognitive Revolution, humans were an unremarkable species in the middle of the food chain. After it, they began their rapid ascent to dominance. The key was not physical strength or individual intelligence but the ability to cooperate flexibly in large groups through shared stories.</p>" },
        { title: "Chapter 2: The Tree of Knowledge", text: "<p>Harari argues that fiction is the foundation of human civilization. Money is a fiction — a piece of paper has no inherent value. Nations are fictions — borders exist only because we agree they do. Human rights are fictions — there is nothing in our biology that grants us inalienable rights.</p><p>But these fictions are not lies. They are shared beliefs that enable cooperation on a massive scale. Two strangers can trade goods because they both believe in the value of money. Millions of people can cooperate in a nation because they share a national myth.</p><p>The ability to create and believe in fictions is what separates Homo sapiens from all other species. Chimpanzees can cooperate in groups of about 150. Humans can cooperate in groups of millions — because they share imagined realities.</p>" },
        { title: "Chapter 3: The Agricultural Revolution", text: "<p>About 10,000 years ago, humans began farming. Harari calls this the biggest fraud in history. Agriculture did not make individual humans better off — it made them worse off. Farmers worked harder, ate less varied diets, and suffered more diseases than hunter-gatherers.</p><p>But agriculture allowed populations to grow. More food meant more people, even if each person was less healthy. The Agricultural Revolution was a trap: once populations grew, there was no going back to hunting and gathering.</p><p>Wheat, Harari argues, domesticated humans rather than the other way around. Humans bent their backs, broke their bodies, and reorganized their entire lives to serve the needs of a plant. The species that was supposed to be the master became the servant.</p>" },
        { title: "Chapter 4: The Unification of Humankind", text: "<p>Over thousands of years, human cultures have been merging into larger and larger units. The forces driving this unification are money, empires, and universal religions — three systems that treat all humans as potentially equal participants.</p><p>Money is the most universal system of mutual trust ever devised. Two people who speak different languages, worship different gods, and follow different customs can still trade using money. It is the one fiction that almost everyone believes in.</p><p>Empires have been the most common form of political organization in history. Despite their reputation for oppression, empires have also been engines of cultural exchange, technological innovation, and legal standardization. Most of today's cultures are the products of imperial legacies.</p>" },
        { title: "Chapter 5: The Scientific Revolution", text: "<p>The Scientific Revolution began around 1500 CE with a simple but revolutionary admission: we do not know everything. Previous civilizations believed they possessed all important knowledge. European scientists admitted their ignorance and set out to discover new things.</p><p>This admission of ignorance, combined with the willingness to invest resources in research, created an unprecedented engine of discovery. Science, empire, and capitalism formed a feedback loop: science provided new technologies, empires provided funding and markets, and capitalism provided the incentive to invest.</p><p>The result was an explosion of power. In 1500, humans were confined to the surface of the earth. By 2000, they had split the atom, walked on the moon, and decoded the genome. No previous civilization had achieved anything comparable.</p>" },
        { title: "Chapter 6: The Marriage of Science and Empire", text: "<p>European imperialism was unique because it was driven by curiosity as much as by greed. When Europeans conquered new territories, they brought scientists along with soldiers. They mapped coastlines, cataloged species, and studied native cultures.</p><p>This marriage of science and empire gave Europeans a decisive advantage. They understood the world better than anyone else, and they used that understanding to dominate it. Knowledge was power in the most literal sense.</p><p>Harari does not romanticize this process. European empires caused immense suffering — slavery, genocide, and cultural destruction. But he insists that we cannot understand the modern world without understanding how science and empire shaped it together.</p>" },
        { title: "Chapter 7: The Capitalist Creed", text: "<p>Capitalism is based on a revolutionary idea: the future will be better than the present. This belief in progress makes it rational to invest — to sacrifice present consumption for future gain. No previous economic system was built on this assumption.</p><p>Credit is the engine of capitalism. A baker borrows money to build a bigger bakery, produces more bread, repays the loan with interest, and everyone is better off. This cycle of investment and growth has produced unprecedented wealth.</p><p>But capitalism has a dark side. It demands perpetual growth, which strains natural resources and creates inequality. It treats everything — including human beings and ecosystems — as potential sources of profit. The question is whether capitalism can be reformed before it destroys the foundations on which it depends.</p>" },
        { title: "Chapter 8: The Industrial Revolution", text: "<p>The Industrial Revolution was fundamentally a revolution in energy conversion. Humans learned to harness the energy stored in fossil fuels and convert it into movement, heat, and electricity. This gave them access to virtually unlimited power.</p><p>The consequences were staggering. In 1800, most humans were farmers. By 2000, most were factory workers, office employees, or service providers. The entire structure of human society was transformed in just two centuries.</p><p>The Industrial Revolution also transformed the family. For thousands of years, the family was the basic unit of production, education, and welfare. Industrialization transferred these functions to the state and the market, weakening family bonds but expanding individual freedom.</p>" },
        { title: "Chapter 9: The Pursuit of Happiness", text: "<p>Has all this progress made us happier? Harari is skeptical. Despite our wealth, technology, and freedom, modern humans do not seem significantly happier than their ancestors. Depression, anxiety, and loneliness are epidemic in the developed world.</p><p>Happiness, research suggests, depends more on expectations than on conditions. A medieval peasant who expected nothing might have been happier than a modern office worker who expects everything. Progress raises expectations faster than it raises conditions.</p><p>Harari suggests that the key to happiness may lie not in changing the world but in changing our minds. Buddhist meditation, which trains the mind to observe its own processes without attachment, may be more effective than any technological innovation.</p>" },
        { title: "Chapter 10: The End of Homo Sapiens", text: "<p>Harari concludes with a startling prediction: Homo sapiens as we know it will soon cease to exist. Biotechnology, artificial intelligence, and cyborg engineering are giving us the power to redesign ourselves — to upgrade our bodies, extend our lifespans, and enhance our cognitive abilities.</p><p>For four billion years, life on earth was governed by natural selection. Now, for the first time, intelligent design is replacing natural selection — not the intelligent design of a god, but the intelligent design of humans.</p><p>This raises profound questions. Who will control these technologies? Will they be available to everyone or only to the rich? What happens when some humans are upgraded and others are not? Sapiens ends not with answers but with the most important question of our time: what do we want to become?</p>" }
      ]
    },
    homodeus: {
      title: "Homo Deus",
      cover: "Assets/Homo Deus cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: The New Human Agenda", text: "<p>For most of history, humanity was preoccupied with three problems: famine, plague, and war. In the twenty-first century, we have largely conquered all three. More people die from eating too much than from eating too little. More people die from old age than from infectious disease.</p><p>With these ancient enemies in retreat, humanity is setting new goals: immortality, happiness, and divinity. We want to live forever, feel good always, and upgrade ourselves into something beyond human.</p><p>Harari calls this the new human agenda. It is not a conspiracy or a plan — it is the natural direction of a species that has solved its basic survival problems and now turns its attention to the ultimate challenges of existence.</p>" },
        { title: "Chapter 2: The Meaning of Life", text: "<p>Humans have always sought meaning through stories — religious narratives, national myths, and personal dramas. These stories give structure to our lives and help us cooperate with strangers.</p><p>But science is undermining these stories. Evolution tells us we are not the pinnacle of creation. Neuroscience tells us we do not have free will. Artificial intelligence tells us we are not the most intelligent beings on the planet.</p><p>If the old stories collapse, what will replace them? Harari argues that the twenty-first century will be defined by the search for new sources of meaning in a world where the old certainties have dissolved.</p>" },
        { title: "Chapter 3: The Human Spark", text: "<p>What makes humans special? For centuries, we believed it was our soul, our consciousness, or our free will. But science has found no evidence for a soul, cannot explain consciousness, and increasingly doubts the existence of free will.</p><p>Harari argues that what made humans dominant was not any individual quality but our ability to cooperate flexibly in large numbers. This ability depends on our capacity for fiction — for creating and believing in shared stories.</p><p>But if algorithms can process information better than human brains, and if they can coordinate behavior more efficiently than human stories, then the human spark may be extinguished. We may become obsolete — not because we are stupid, but because we are no longer the best information processors available.</p>" },
        { title: "Chapter 4: The Storytellers", text: "<p>Human history is the history of stories. The Agricultural Revolution was powered by myths about gods and harvests. The Scientific Revolution was powered by stories about progress and discovery. The modern economy is powered by the story of perpetual growth.</p><p>These stories are not true in any objective sense, but they are real in their effects. Millions of people organize their lives around them, fight for them, and die for them. The power of a story is measured not by its truth but by its ability to organize human behavior.</p><p>Harari warns that the stories of the twenty-first century will be written not by humans but by algorithms. When artificial intelligence can tell better stories than human authors — stories tailored to each individual's psychology — the age of human storytelling may come to an end.</p>" },
        { title: "Chapter 5: The Odd Couple", text: "<p>Science and religion have been locked in a complex relationship for centuries. They are often portrayed as enemies, but Harari argues they are more like an odd couple — they need each other more than they admit.</p><p>Science provides power but not meaning. It can tell us how to build a nuclear bomb but not whether we should. Religion provides meaning but not power. It can tell us that life is sacred but not how to cure cancer.</p><p>The modern world needs both. But as science grows more powerful, it increasingly encroaches on religion's territory — answering questions about consciousness, morality, and the nature of reality that were once the exclusive domain of faith.</p>" },
        { title: "Chapter 6: The Modern Covenant", text: "<p>Modernity is a deal: humans agree to give up meaning in exchange for power. Pre-modern cultures believed the universe had a grand plan and that human life had a predetermined purpose. Modern culture says there is no plan — but we can do anything we want.</p><p>This deal has been extraordinarily productive. By abandoning the search for cosmic meaning, humans freed themselves to pursue knowledge, wealth, and power without limit. The result is the modern world — powerful beyond imagination but haunted by a sense of meaninglessness.</p><p>The question is whether this deal is sustainable. Can humans live without meaning? Or will the absence of purpose eventually undermine the very civilization that the modern covenant created?</p>" },
        { title: "Chapter 7: The Humanist Revolution", text: "<p>Humanism filled the void left by the retreat of religion. It declared that human feelings and experiences are the ultimate source of meaning. A painting is beautiful if it moves you. An action is moral if it feels right. A life is meaningful if you find it meaningful.</p><p>Humanism comes in three flavors: liberal humanism (individual feelings matter most), socialist humanism (collective feelings matter most), and evolutionary humanism (the feelings of superior humans matter most).</p><p>Liberal humanism won the twentieth century's ideological wars. But it is now under threat from the same science that empowered it. If algorithms can understand our feelings better than we can, then the humanist project — the idea that each person is the best judge of their own experience — collapses.</p>" },
        { title: "Chapter 8: The Time Bomb in the Laboratory", text: "<p>Science is dismantling the foundations of liberal humanism. Neuroscience reveals that our decisions are made by neural processes before we become conscious of them. There is no single self making choices — there are competing neural systems producing the illusion of a unified will.</p><p>If free will is an illusion, then the entire liberal project is built on sand. Democracy assumes voters can make rational choices. The free market assumes consumers know what they want. Human rights assume individuals have inherent dignity. All of these depend on free will.</p><p>Harari does not claim that liberalism is wrong — only that its scientific foundations are crumbling. The twenty-first century will need to find new justifications for human dignity, or abandon the concept altogether.</p>" },
        { title: "Chapter 9: The Great Decoupling", text: "<p>Throughout history, intelligence and consciousness were coupled — you needed a conscious mind to perform intelligent tasks. But artificial intelligence is decoupling them. Algorithms can drive cars, diagnose diseases, and trade stocks without any conscious experience.</p><p>This decoupling threatens to make most humans economically useless. If algorithms can do everything better and cheaper than humans, what role is left for us? We may face a future with a tiny elite of upgraded humans and a vast 'useless class' with nothing to contribute.</p><p>The great political question of the twenty-first century will not be exploitation but irrelevance. It is worse to be exploited than to be irrelevant — at least the exploited are needed.</p>" },
        { title: "Chapter 10: The Data Religion", text: "<p>Harari identifies a new religion emerging in the twenty-first century: Dataism. Dataism declares that the universe consists of data flows, and that the value of any phenomenon is determined by its contribution to data processing.</p><p>From a Dataist perspective, Beethoven's Fifth Symphony is a pattern of data, the stock market is a data-processing system, and human beings are biological algorithms. The highest good is to maximize the flow and freedom of information.</p><p>Homo Deus ends with a haunting question: if Dataism succeeds, what happens to human experience? If algorithms know us better than we know ourselves, if they make better decisions than we can, if they create better art than we can — then what is left for Homo sapiens? Perhaps the answer is: nothing. Perhaps the age of humans is ending, and the age of data is beginning.</p>" }
      ]
    },
    lessons21: {
      title: "21 Lessons for the 21st Century",
      cover: "Assets/21 Lessons for the 21st Century cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: Disillusionment", text: "<p>The great political stories of the twentieth century have collapsed. Fascism was defeated in 1945. Communism fell in 1991. Liberalism seemed triumphant — but now it too is losing credibility. People around the world are losing faith in the liberal story of progress, freedom, and globalization.</p><p>The result is disillusionment. Without a compelling story about where humanity is heading, people feel lost and anxious. They turn to nostalgia, nationalism, and conspiracy theories — anything that offers a sense of meaning and direction.</p><p>Harari argues that we need a new story — one that acknowledges the challenges of the twenty-first century without retreating into the fantasies of the past. But creating such a story requires honesty about what we know and what we do not.</p>" },
        { title: "Chapter 2: Work and Technology", text: "<p>Artificial intelligence and automation will transform the job market more profoundly than any previous technological revolution. Not just manual labor but cognitive work — legal analysis, medical diagnosis, financial trading — will be performed by algorithms.</p><p>The question is not whether jobs will be lost but whether new jobs will be created fast enough to replace them. Previous revolutions created more jobs than they destroyed, but this time may be different. AI can learn and adapt faster than humans can retrain.</p><p>Harari suggests that governments need to invest massively in education and social safety nets. Universal basic income may become necessary. But the deeper challenge is psychological: in a world where work is optional, how do people find purpose and identity?</p>" },
        { title: "Chapter 3: Liberty and Big Data", text: "<p>Liberal democracy depends on the idea that individuals are the best judges of their own interests. But what happens when algorithms know you better than you know yourself? When your phone can predict your mood, your purchases, and your vote?</p><p>Big data threatens to undermine democracy by enabling manipulation on an unprecedented scale. If a political campaign can target each voter with personalized messages designed to exploit their specific psychological vulnerabilities, then elections become exercises in manipulation rather than deliberation.</p><p>Harari warns that the combination of biotechnology and information technology could create digital dictatorships that make twentieth-century totalitarianism look primitive. The surveillance tools available today would have been Stalin's dream.</p>" },
        { title: "Chapter 4: Equality and Ownership", text: "<p>The great political struggle of the twenty-first century will be over the ownership of data. In the twentieth century, the key question was who owns the means of production — land, factories, and machines. In the twenty-first century, the key question is who owns the data.</p><p>If data is concentrated in the hands of a few corporations or governments, inequality will reach levels never seen before. Those who control the data will control the future — they will be able to engineer life itself while the rest of humanity becomes irrelevant.</p><p>Harari argues for the regulation of data ownership, but acknowledges that this is an enormously complex challenge. Data does not behave like land or oil — it can be copied infinitely, it crosses borders effortlessly, and its value depends on context.</p>" },
        { title: "Chapter 5: Community and Civilization", text: "<p>Humans evolved to live in small communities of a few dozen people. Modern civilization requires us to cooperate with millions of strangers. This mismatch between our evolutionary heritage and our current reality creates loneliness, anxiety, and social fragmentation.</p><p>Online communities promise to fill the gap, but they often make things worse. Social media creates the illusion of connection while deepening isolation. People have thousands of online friends but no one to call in an emergency.</p><p>Harari suggests that rebuilding genuine community requires physical presence, shared experiences, and mutual vulnerability — things that cannot be replicated online. The challenge is to create communities that are both intimate enough to satisfy our evolutionary needs and open enough to function in a global civilization.</p>" },
        { title: "Chapter 6: Nationalism and Globalism", text: "<p>Nationalism is making a comeback, but the problems of the twenty-first century — climate change, nuclear war, technological disruption — are global in nature. No nation can solve them alone. Yet global cooperation requires trust, and trust is in short supply.</p><p>Harari argues that nationalism is not inherently evil — it has provided identity, solidarity, and social welfare to billions of people. But it becomes dangerous when it claims that one nation is superior to all others or that national interests should override global concerns.</p><p>The solution is not to abolish nations but to create a global identity that complements national identities. We need to be both patriots and cosmopolitans — loyal to our communities and responsible to the world.</p>" },
        { title: "Chapter 7: Religion and Secularism", text: "<p>Religion remains a powerful force in the twenty-first century, but its role has changed. It is no longer the primary source of knowledge about the world — science has taken that role. Instead, religion provides identity, community, and moral guidance.</p><p>Harari defines secularism not as the absence of religion but as a commitment to truth, compassion, equality, freedom, courage, and responsibility. A secular person does not reject all values — they insist that values must be based on evidence and reason rather than divine authority.</p><p>The tension between religion and secularism will continue, but Harari argues that the real divide is not between believers and non-believers but between those who are willing to question their own beliefs and those who are not.</p>" },
        { title: "Chapter 8: Ignorance and Justice", text: "<p>We know far less than we think we do. Most of our opinions are based not on personal research but on group loyalty. We adopt the views of our tribe — our political party, our social class, our nation — and defend them as if they were our own.</p><p>This is not a bug but a feature. Individual humans are not designed to understand complex systems. We are designed to cooperate in groups, and group cooperation requires shared beliefs — even if those beliefs are wrong.</p><p>Harari argues that intellectual humility is the most important virtue of the twenty-first century. We must learn to say 'I don't know' more often, to seek out information that challenges our views, and to change our minds when the evidence demands it.</p>" },
        { title: "Chapter 9: Post-Truth and Propaganda", text: "<p>The term 'post-truth' suggests that we have entered a new era of lies and propaganda. But Harari points out that humans have always lived in a post-truth world. Religions, nations, and ideologies have always been based on fictions rather than facts.</p><p>What is new is not the existence of propaganda but its sophistication. Modern technology allows lies to spread faster, reach further, and be targeted more precisely than ever before. A single fake news story can reach millions of people in hours.</p><p>The antidote to post-truth is not more information but better thinking. We need to invest in education that teaches critical thinking, media literacy, and the ability to distinguish between reliable and unreliable sources of information.</p>" },
        { title: "Chapter 10: Meditation and Meaning", text: "<p>Harari concludes with a personal note. He practices Vipassana meditation — a technique that involves observing the sensations of the body without reacting to them. This practice, he says, has been the most important thing in his life.</p><p>Meditation teaches you to observe your own mind without being controlled by it. You learn that your thoughts and feelings are not you — they are passing phenomena that arise and disappear. This insight is liberating: if you are not your anger, you do not have to act on it.</p><p>In a world of increasing complexity and uncertainty, the ability to know your own mind may be the most valuable skill of all. Algorithms may know your behavior better than you do, but only you can observe your own consciousness from the inside. This inner knowledge — this self-awareness — may be humanity's last and most important frontier.</p>" }
      ]
    }
  };

  var currentBook = null, currentPage = 0;

  function openBook(k) { currentBook = books[k]; if (!currentBook) return; currentPage = 0; document.getElementById("readerOverlay").classList.add("active"); document.body.style.overflow = "hidden"; renderPage(); }
  function closeBook() { document.getElementById("readerOverlay").classList.remove("active"); document.body.style.overflow = ""; currentBook = null; }
  function renderPage() {
    if (!currentBook) return;
    var ch = currentBook.chapters[currentPage], ci = document.getElementById("readerCoverImg"), ce = document.getElementById("readerChapter"), ti = document.getElementById("chapterTitle"), te = document.getElementById("chapterText"), ind = document.getElementById("readerIndicator"), rt = document.getElementById("readerTitle"), pb = document.getElementById("readerPrev"), nb = document.getElementById("readerNext");
    if (ch.type === "cover") { ci.style.display="block"; ci.src=currentBook.cover; ce.classList.remove("visible"); rt.textContent=currentBook.title; }
    else { ci.style.display="none"; ce.classList.add("visible"); ti.textContent=ch.title; te.innerHTML=ch.text; rt.textContent=ch.title; ce.scrollTop=0; }
    ind.textContent=(currentPage+1)+" / "+currentBook.chapters.length; pb.disabled=currentPage===0; nb.disabled=currentPage===currentBook.chapters.length-1;
  }

  document.querySelectorAll(".book-read-btn").forEach(function(b){b.addEventListener("click",function(){openBook(b.dataset.book);});});
  document.getElementById("readerBackBtn").addEventListener("click",closeBook);
  document.getElementById("readerPrev").addEventListener("click",function(){if(currentBook&&currentPage>0){currentPage--;renderPage();}});
  document.getElementById("readerNext").addEventListener("click",function(){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}});
  document.addEventListener("keydown",function(e){if(!document.getElementById("readerOverlay").classList.contains("active"))return;if(e.key==="ArrowRight"){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}}else if(e.key==="ArrowLeft"){if(currentBook&&currentPage>0){currentPage--;renderPage();}}else if(e.key==="Escape"){closeBook();}});
  var scrollCD=false;document.getElementById("readerOverlay").addEventListener("wheel",function(e){if(!currentBook||scrollCD)return;var ce=document.getElementById("readerChapter");if(currentPage===0||!ce.classList.contains("visible")){e.preventDefault();scrollCD=true;if(e.deltaY>0&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}else if(e.deltaY<0&&currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);return;}var aT=ce.scrollTop<=0,aB=ce.scrollTop+ce.clientHeight>=ce.scrollHeight-5;if(aB&&e.deltaY>0){e.preventDefault();scrollCD=true;if(currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}setTimeout(function(){scrollCD=false;},200);}else if(aT&&e.deltaY<0){e.preventDefault();scrollCD=true;if(currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);}},{passive:false});

  // ===================== 3D MODEL =====================
  var container = document.getElementById("modelContainer");
  var w = container.clientWidth, h = container.clientHeight;
  var scene = new THREE.Scene();
  var camera = new THREE.PerspectiveCamera(45, w/h, 0.01, 100);
  camera.position.set(0, 1, 3);
  var renderer = new THREE.WebGLRenderer({ antialias:true, alpha:true });
  renderer.setClearColor(0x000000, 0);
  renderer.setSize(w, h);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  container.appendChild(renderer.domElement);
  var controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping=true; controls.dampingFactor=0.05; controls.autoRotate=true; controls.autoRotateSpeed=2; controls.enableZoom=false; controls.target.set(0,0.8,0);
  scene.add(new THREE.AmbientLight(0xffffff,0.6));
  var dl=new THREE.DirectionalLight(0xffffff,1.5); dl.position.set(2,4,3); scene.add(dl);
  var fl=new THREE.DirectionalLight(0xffeedd,0.5); fl.position.set(-2,2,-1); scene.add(fl);
  scene.add(new THREE.HemisphereLight(0xffeeb1,0x080820,0.3));
  var loader=new THREE.GLTFLoader();
  loader.load("Assets/Yuval Noah Harari.glb",function(g){var m=g.scene;var b=new THREE.Box3().setFromObject(m);var c=b.getCenter(new THREE.Vector3());var s=b.getSize(new THREE.Vector3());var mx=Math.max(s.x,s.y,s.z);var sc=2/mx;m.scale.setScalar(sc);m.position.sub(c.multiplyScalar(sc));m.position.y+=0.5;scene.add(m);controls.target.set(0,m.position.y+(s.y*sc)/2,0);},undefined,function(e){console.warn("Failed to load model:",e);});
  function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();
  window.addEventListener("resize",function(){var w2=container.clientWidth,h2=container.clientHeight;camera.aspect=w2/h2;camera.updateProjectionMatrix();renderer.setSize(w2,h2);});
})();
