(function() {
  "use strict";

  document.getElementById("booksBtn").addEventListener("click", function() {
    document.getElementById("booksSection").scrollIntoView({ behavior: "smooth" });
  });

  // ===================== READER SYSTEM =====================
  var books = {
    metamorphosis: {
      title: "The Metamorphosis",
      cover: "Assets/The Metamorphosis cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: The Transformation", text: "<p>Gregor Samsa wakes one morning to find himself transformed into a monstrous insect. His first thought is not horror at his condition but anxiety about missing his train to work. He is a traveling salesman, and he cannot afford to be late.</p><p>He examines his new body — the hard shell, the many legs, the brown belly — with a strange detachment. He tries to go back to sleep, hoping the transformation will reverse itself. But his insect body will not cooperate with his human habits.</p><p>This opening is one of the most famous in literature. Kafka presents the impossible as matter-of-fact, forcing the reader to accept the absurd premise and focus on its human consequences. The horror is not the transformation itself but the world's response to it.</p>" },
        { title: "Chapter 2: The Family's Discovery", text: "<p>Gregor's family grows worried when he does not emerge for breakfast. His mother calls through the door, his father knocks impatiently, and his sister Grete pleads with him. The office manager arrives to investigate his absence.</p><p>When Gregor finally manages to open the door, the reaction is immediate and devastating. His mother faints, the office manager flees in horror, and his father drives him back into his room with a rolled-up newspaper.</p><p>The scene is both terrifying and darkly comic. Gregor's main concern is still his job — he tries to explain to the office manager that he will be at work soon. His human mind is trapped in an inhuman body, and no one can hear his words, only his insect chirping.</p>" },
        { title: "Chapter 3: Grete's Care", text: "<p>Gregor's sister Grete takes on the role of caretaker. She brings him food, discovering that he now prefers rotting scraps to fresh meals. She cleans his room and tries to make him comfortable, though she cannot bear to look at him.</p><p>Grete's care is genuine but limited. She treats Gregor more like a pet than a brother. She refers to his preferences and habits but never speaks to him directly. The human connection between them is fading.</p><p>Gregor adapts to his new body. He learns to crawl on the walls and ceiling, finding pleasure in hanging upside down. But each adaptation takes him further from his humanity. The more comfortable he becomes as an insect, the less recognizable he is as Gregor.</p>" },
        { title: "Chapter 4: The Furniture Removal", text: "<p>Grete and her mother decide to remove the furniture from Gregor's room to give him more space to crawl. But Gregor is distressed — the furniture represents his human life, his memories, his identity.</p><p>He clings to a picture on the wall — a woman in furs that he had cut from a magazine and framed. This small act of resistance is his last attempt to hold onto his humanity. He presses his body against the glass, refusing to let them take it.</p><p>His mother sees him on the wall and faints. When his father returns, he attacks Gregor with apples, lodging one in his back. The apple wound festers and becomes a permanent injury — a mark of his father's violence that will hasten his death.</p>" },
        { title: "Chapter 5: The Lodgers", text: "<p>The family's financial situation deteriorates. Without Gregor's income, they must take in three lodgers to help pay the rent. The lodgers are demanding and particular, and the family caters to their every whim.</p><p>Gregor is increasingly neglected. His room becomes a storage space for unwanted items. Grete no longer cleans regularly. The food she leaves is often untouched — Gregor is losing his appetite along with his will to live.</p><p>The family that once depended on Gregor now treats him as a burden and a shame. The transformation has reversed the family dynamics: the provider has become the dependent, and the dependents have become the providers.</p>" },
        { title: "Chapter 6: Grete's Violin", text: "<p>One evening, Grete plays her violin for the lodgers. Gregor, drawn by the music, crawls out of his room into the living area. The music moves him deeply — he feels that it is showing him the way to an unknown nourishment he craves.</p><p>This is one of Kafka's most poignant scenes. The insect responds to beauty more deeply than the human lodgers, who quickly lose interest in the performance. Gregor's soul is still human even as his body is not.</p><p>But the lodgers see Gregor and are horrified. They threaten to leave without paying and to sue the family for the disgusting conditions. The family's shame and financial anxiety reach a breaking point.</p>" },
        { title: "Chapter 7: Grete's Declaration", text: "<p>Grete, who was once Gregor's most devoted caretaker, makes a devastating declaration: the creature in the room is no longer her brother. If it were Gregor, she argues, he would have left voluntarily, understanding that human beings cannot live with such a creature.</p><p>She insists that the family must get rid of it. Her father agrees. Her mother is too weak to object. The family has reached a consensus: Gregor must go.</p><p>This is the cruelest moment in the story. The person who knew Gregor best, who cared for him longest, is the one who finally denies his humanity. Grete's declaration is not just a practical decision — it is an act of erasure.</p>" },
        { title: "Chapter 8: Gregor's Death", text: "<p>Gregor crawls back to his room, understanding that he must disappear. The apple lodged in his back has become infected, his body is failing, and he can barely move. He thinks of his family with tenderness and love.</p><p>He dies in the early hours of the morning, his body dried out and flat. The cleaning woman discovers him and announces his death casually: 'It's croaked.' The family receives the news with relief.</p><p>Gregor's death is quiet and lonely. There is no dramatic final scene, no reconciliation, no recognition of his sacrifice. He dies as he lived in his final months — unseen, unheard, and unloved.</p>" },
        { title: "Chapter 9: The Family's Liberation", text: "<p>After Gregor's death, the family experiences an immediate sense of relief and renewal. They take a day off work, write letters of excuse, and go for a tram ride into the countryside.</p><p>On the tram, the parents notice that Grete has grown into a beautiful young woman. They exchange knowing glances — it is time to find her a husband. The future suddenly seems bright and full of possibility.</p><p>The contrast with Gregor's lonely death is devastating. The family does not mourn — they celebrate. Gregor's sacrifice, which sustained them for years, is forgotten the moment it is no longer needed.</p>" },
        { title: "Chapter 10: The Meaning of Metamorphosis", text: "<p>The Metamorphosis resists simple interpretation. It is about alienation — the feeling of being trapped in a body, a job, a family that does not understand you. It is about the expendability of the individual in modern society.</p><p>It is also about the nature of identity. When does Gregor stop being Gregor? When his body changes? When his family stops recognizing him? When he stops recognizing himself? Kafka leaves these questions unanswered.</p><p>The story's power lies in its refusal to explain. Kafka never tells us why Gregor transforms or what it means. The metamorphosis simply happens, as absurd and inexplicable as life itself. We are left to make our own meaning from the wreckage — just as Gregor's family is left to make a new life from the ruins of the old one.</p>" }
      ]
    },
    trial: {
      title: "The Trial",
      cover: "Assets/The trail Cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: The Arrest", text: "<p>Josef K. wakes on the morning of his thirtieth birthday to find two warders in his room. They inform him that he is under arrest, though they cannot tell him what he is charged with. The arrest is real but strange — he is not taken to prison but allowed to continue his normal life.</p><p>K. is outraged. He is a respectable bank officer with no criminal record. He demands to see their authorization, to speak to their superiors, to understand what is happening. But the warders are indifferent to his protests.</p><p>This opening establishes the novel's central nightmare: a legal system that operates without transparency, without logic, and without mercy. K. is guilty — but of what? No one will say, and perhaps no one knows.</p>" },
        { title: "Chapter 2: The First Hearing", text: "<p>K. is summoned to his first hearing in a shabby tenement building on a Sunday morning. He arrives late and finds a crowded courtroom filled with people wearing badges — members of the court who are indistinguishable from ordinary citizens.</p><p>K. delivers an impassioned speech denouncing the court as corrupt and absurd. The audience seems sympathetic, but K. gradually realizes that they are all part of the system. His speech has changed nothing.</p><p>The hearing reveals the court's true nature: it is everywhere and nowhere, embedded in the fabric of ordinary life. There is no separate building, no formal procedure, no clear authority. The court is a shadow that falls across everything.</p>" },
        { title: "Chapter 3: The Lawyer", text: "<p>K. hires a lawyer named Huld, who is bedridden and seems more interested in his own importance than in K.'s case. Huld explains that the court's proceedings are secret, that the charges are never fully revealed, and that the best strategy is patience and submission.</p><p>K. is frustrated by Huld's passivity. The lawyer files petitions that are never read, cultivates connections that lead nowhere, and counsels K. to wait — always to wait. Progress is measured in decades, not months.</p><p>The legal system Kafka describes is a perfect bureaucracy: it exists to perpetuate itself, not to achieve justice. Every action generates more paperwork, more hearings, more delays. The process is the punishment.</p>" },
        { title: "Chapter 4: The Painter Titorelli", text: "<p>K. visits Titorelli, the court painter, hoping to find an alternative path to acquittal. Titorelli explains that there are three possible outcomes: definite acquittal, apparent acquittal, and indefinite postponement.</p><p>Definite acquittal is theoretically possible but has never actually occurred. Apparent acquittal means the charges are temporarily dropped but can be reinstated at any time. Indefinite postponement means the case remains permanently in its early stages.</p><p>None of these options offer real freedom. The accused can never truly escape the court — they can only manage their relationship with it. K. begins to understand that his trial is not an event but a condition, not something that happens to him but something he is.</p>" },
        { title: "Chapter 5: The Whipper", text: "<p>K. opens a storage closet at his bank and discovers the two warders from his arrest being whipped by a man in leather. They are being punished because K. complained about their behavior during his arrest.</p><p>K. is horrified — he never intended for them to be punished. He tries to intervene, but the whipper is implacable. The next day, K. opens the same closet and finds the same scene repeating, as if frozen in time.</p><p>This surreal episode reveals the court's cruelty and K.'s complicity in it. His attempt to assert his rights has caused suffering to others. In the court's system, every action has unintended consequences, and innocence is impossible.</p>" },
        { title: "Chapter 6: K.'s Uncle", text: "<p>K.'s uncle arrives from the country, alarmed by rumors of the trial. He drags K. to see the lawyer Huld, insisting that the family's reputation is at stake. The uncle treats the trial as a social embarrassment rather than a legal matter.</p><p>At Huld's apartment, K. meets Leni, the lawyer's nurse, who seduces him. K. is drawn to her despite knowing that she seduces all of Huld's clients. His uncle is furious — K. is not taking his situation seriously enough.</p><p>The episode shows how the trial infiltrates every aspect of K.'s life. His family relationships, his romantic encounters, his professional standing — everything is contaminated by the invisible proceedings against him.</p>" },
        { title: "Chapter 7: The Cathedral", text: "<p>K. is sent to show an Italian client around the cathedral. But the client never appears. Instead, K. finds himself alone in the vast, dark building with a prison chaplain who has been waiting for him.</p><p>The chaplain tells K. the parable 'Before the Law': a man spends his entire life waiting at the gate of the Law, only to be told at the moment of death that the gate was meant for him alone and is now being closed.</p><p>This parable is the heart of the novel. The Law exists for each person individually, yet no one can enter it. The gate is always open but always guarded. The man's patience and obedience are rewarded with nothing. The system promises justice but delivers only waiting.</p>" },
        { title: "Chapter 8: Dismissing the Lawyer", text: "<p>K. decides to dismiss Huld and take control of his own defense. He visits the lawyer to deliver the news and finds another client, Block, who has been pursuing his case for five years with six different lawyers.</p><p>Block is a broken man — he has sacrificed his business, his dignity, and his independence to the court. He grovels before Huld, kissing his hand and begging for scraps of information about his case. He is what K. might become.</p><p>K. is repulsed but also frightened. He sees in Block the logical endpoint of submission to the court. If he does not act decisively, he will be consumed by the process just as Block has been.</p>" },
        { title: "Chapter 9: The Year Passes", text: "<p>As the months pass, K.'s trial increasingly dominates his life. His work at the bank suffers. His relationships deteriorate. He becomes obsessed with his case, spending hours researching legal strategies that lead nowhere.</p><p>The court does not need to imprison K. — it imprisons him through anxiety, uncertainty, and the endless demands of the process. He is free to go anywhere, but he cannot escape the trial because the trial is inside him.</p><p>K. begins to accept his guilt — not because he has done anything wrong, but because the court's authority is so pervasive that resistance seems futile. The system does not need evidence; it needs only the accused's eventual submission.</p>" },
        { title: "Chapter 10: The Execution", text: "<p>On the evening before his thirty-first birthday, two men in frock coats arrive at K.'s apartment. They take him by the arms and lead him through the streets to a quarry on the outskirts of the city.</p><p>K. does not resist. He has been expecting them. At the quarry, one man holds him while the other produces a butcher's knife. K.'s last thought is of shame — he dies 'like a dog,' and the shame, he feels, will outlive him.</p><p>The Trial ends without resolution, without explanation, without justice. K. never learns what he was charged with. The court never reveals its reasoning. Kafka's novel is a portrait of modern existence: we are all on trial, all guilty, and none of us will ever know why.</p>" }
      ]
    },
    castle: {
      title: "The Castle",
      cover: "Assets/The Castle cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: Arrival in the Village", text: "<p>K. arrives late at night in a village dominated by a castle on the hill above. He claims to be a land surveyor summoned by the castle authorities. The villagers are skeptical — no one was expecting a land surveyor.</p><p>K. calls the castle to confirm his appointment. After contradictory responses, the castle acknowledges him — but the acknowledgment feels arbitrary, as if they are simply accepting his claim rather than confirming it.</p><p>From the first pages, Kafka establishes the novel's central dynamic: K. seeks recognition from an authority that is simultaneously present and absent, powerful and indifferent. The castle looms over everything but remains forever out of reach.</p>" },
        { title: "Chapter 2: The Castle Officials", text: "<p>K. learns that the castle operates through an elaborate bureaucracy of officials, secretaries, and messengers. The most important official connected to his case is Klamm — a mysterious figure whom K. desperately wants to meet.</p><p>But meeting Klamm proves impossible. He is always in the next room, always just leaving, always unavailable. K. catches glimpses of him through keyholes but can never speak to him directly.</p><p>Klamm represents the ultimate authority — the person who could resolve K.'s situation with a single word. But that word never comes. The bureaucracy exists to prevent direct contact between the individual and the authority they seek.</p>" },
        { title: "Chapter 3: Frieda", text: "<p>K. meets Frieda, a barmaid at the Herrenhof inn who is Klamm's mistress. She is drawn to K. and abandons Klamm for him. They begin a relationship that is both genuine and strategic — K. hopes that Frieda's connection to Klamm will help his case.</p><p>Frieda is a complex character. She has status in the village because of her relationship with Klamm, and by leaving him for K., she sacrifices her position. Yet she does it willingly, perhaps hoping that K. offers something Klamm cannot — genuine human connection.</p><p>Their relationship is tender but unstable. K. cannot fully commit to Frieda because he is consumed by his quest to reach the castle. Frieda cannot fully trust K. because she suspects he is using her.</p>" },
        { title: "Chapter 4: The Assistants", text: "<p>The castle assigns K. two assistants — Artur and Jeremias — who are childish, incompetent, and constantly underfoot. They follow K. everywhere, interfere with his plans, and seem designed to obstruct rather than help.</p><p>K. suspects that the assistants are spies sent by the castle to monitor him. But they are so clumsy and obvious that they seem more like a joke than a threat. Their presence adds an element of absurd comedy to K.'s increasingly desperate situation.</p><p>The assistants represent the castle's method of control: not through force but through interference, distraction, and the constant erosion of the individual's ability to act independently.</p>" },
        { title: "Chapter 5: The School", text: "<p>K. is offered a position as the village school janitor — a humiliating job for a land surveyor. He accepts it because it gives him a place to live and a foothold in the village. He and Frieda move into the school.</p><p>The conditions are miserable. They sleep on the floor of a classroom, surrounded by gymnastic equipment. The teacher is hostile, the children are unruly, and K.'s assistants make everything worse.</p><p>K.'s descent from land surveyor to janitor mirrors his diminishing status in the village. The castle has not rejected him outright — it has simply assigned him a role so far beneath his expectations that acceptance feels like defeat.</p>" },
        { title: "Chapter 6: Barnabas and His Family", text: "<p>K. befriends Barnabas, a young man who serves as a messenger between K. and the castle. But Barnabas's messages are unreliable — they may be official communications or they may be meaningless scraps that Barnabas has picked up by accident.</p><p>Barnabas's family has been ostracized by the village because his sister Amalia once refused the advances of a castle official. The family's punishment is not formal — there is no decree, no trial. They are simply shunned, gradually excluded from village life.</p><p>The Barnabas family's story reveals the castle's true power: it does not need to punish directly. The village punishes on its behalf, enforcing an unwritten code of submission that is more effective than any law.</p>" },
        { title: "Chapter 7: Amalia's Defiance", text: "<p>Amalia's story is the novel's most powerful episode. A castle official sent her a vulgar letter demanding that she come to him. Amalia tore up the letter — an act of defiance that no one in the village had ever dared.</p><p>The consequences were devastating. The family lost their livelihood, their friends, and their standing in the community. Amalia's father spent years petitioning the castle for forgiveness, destroying his health in the process.</p><p>Amalia is the only character in the novel who refuses to submit to the castle's authority. Her defiance is heroic but costly. Kafka suggests that resistance to an unjust system is possible but that the price may be unbearable.</p>" },
        { title: "Chapter 8: The Herrenhof at Night", text: "<p>K. waits in the corridor of the Herrenhof inn, hoping to intercept Klamm. He waits for hours in the cold, watching officials come and go, but Klamm never appears. A secretary named Erlanger summons K. instead.</p><p>Erlanger gives K. a trivial task: ensure that Frieda returns to her position as barmaid. The castle's concern is not with K.'s appointment as land surveyor but with maintaining the smooth operation of its social machinery.</p><p>This episode crystallizes K.'s predicament. He seeks recognition and purpose from the castle, but the castle sees him only as a minor disruption to be managed. His existential crisis is, from the castle's perspective, an administrative inconvenience.</p>" },
        { title: "Chapter 9: Pepi", text: "<p>Frieda leaves K. and returns to Klamm. Her replacement at the bar is Pepi, a young chambermaid who sees the barmaid position as a tremendous promotion. Pepi tells K. her version of events, suggesting that Frieda orchestrated everything.</p><p>Pepi's perspective reveals how differently each character experiences the same events. What K. sees as a love story, Pepi sees as a power play. What K. sees as a quest for justice, the villagers see as foolish stubbornness.</p><p>K. is left alone, without Frieda, without progress on his case, without any clear path forward. The castle remains on the hill, visible but unreachable, its purposes as opaque as ever.</p>" },
        { title: "Chapter 10: The Unfinished Journey", text: "<p>The Castle was left unfinished at Kafka's death. According to his friend Max Brod, Kafka intended K. to die of exhaustion in the village, never having reached the castle. On his deathbed, a message would arrive granting him permission to stay.</p><p>This intended ending is perfectly Kafkaesque: recognition arrives only when it is too late to matter. The system grants what was asked for only after the asking has destroyed the asker.</p><p>The Castle remains one of literature's great unfinished works — and its incompleteness feels appropriate. K.'s quest has no resolution because the quest itself is the point. The castle cannot be reached because it was never meant to be reached. It exists only as an object of longing, a promise that is never fulfilled, a door that is always almost open.</p>" }
      ]
    }
  };

  var currentBook = null, currentPage = 0;

  function openBook(k) { currentBook = books[k]; if (!currentBook) return; currentPage = 0; document.getElementById("readerOverlay").classList.add("active"); document.body.style.overflow = "hidden"; renderPage(); }
  function closeBook() { document.getElementById("readerOverlay").classList.remove("active"); document.body.style.overflow = ""; currentBook = null; }
  function renderPage() {
    if (!currentBook) return;
    var ch = currentBook.chapters[currentPage], ci = document.getElementById("readerCoverImg"), ce = document.getElementById("readerChapter"), ti = document.getElementById("chapterTitle"), te = document.getElementById("chapterText"), ind = document.getElementById("readerIndicator"), rt = document.getElementById("readerTitle"), pb = document.getElementById("readerPrev"), nb = document.getElementById("readerNext");
    if (ch.type === "cover") { ci.style.display="block"; ci.src=currentBook.cover; ce.classList.remove("visible"); rt.textContent=currentBook.title; }
    else { ci.style.display="none"; ce.classList.add("visible"); ti.textContent=ch.title; te.innerHTML=ch.text; rt.textContent=ch.title; ce.scrollTop=0; }
    ind.textContent=(currentPage+1)+" / "+currentBook.chapters.length; pb.disabled=currentPage===0; nb.disabled=currentPage===currentBook.chapters.length-1;
  }

  document.querySelectorAll(".book-read-btn").forEach(function(b){b.addEventListener("click",function(){openBook(b.dataset.book);});});
  document.getElementById("readerBackBtn").addEventListener("click",closeBook);
  document.getElementById("readerPrev").addEventListener("click",function(){if(currentBook&&currentPage>0){currentPage--;renderPage();}});
  document.getElementById("readerNext").addEventListener("click",function(){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}});
  document.addEventListener("keydown",function(e){if(!document.getElementById("readerOverlay").classList.contains("active"))return;if(e.key==="ArrowRight"){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}}else if(e.key==="ArrowLeft"){if(currentBook&&currentPage>0){currentPage--;renderPage();}}else if(e.key==="Escape"){closeBook();}});
  var scrollCD=false;document.getElementById("readerOverlay").addEventListener("wheel",function(e){if(!currentBook||scrollCD)return;var ce=document.getElementById("readerChapter");if(currentPage===0||!ce.classList.contains("visible")){e.preventDefault();scrollCD=true;if(e.deltaY>0&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}else if(e.deltaY<0&&currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);return;}var aT=ce.scrollTop<=0,aB=ce.scrollTop+ce.clientHeight>=ce.scrollHeight-5;if(aB&&e.deltaY>0){e.preventDefault();scrollCD=true;if(currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}setTimeout(function(){scrollCD=false;},200);}else if(aT&&e.deltaY<0){e.preventDefault();scrollCD=true;if(currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);}},{passive:false});

  // ===================== 3D MODEL =====================
  var container = document.getElementById("modelContainer");
  var w = container.clientWidth, h = container.clientHeight;
  var scene = new THREE.Scene();
  var camera = new THREE.PerspectiveCamera(45, w/h, 0.01, 100);
  camera.position.set(0, 1, 3);
  var renderer = new THREE.WebGLRenderer({ antialias:true, alpha:true });
  renderer.setClearColor(0x000000, 0);
  renderer.setSize(w, h);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  container.appendChild(renderer.domElement);
  var controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping=true; controls.dampingFactor=0.05; controls.autoRotate=true; controls.autoRotateSpeed=2; controls.enableZoom=false; controls.target.set(0,0.8,0);
  scene.add(new THREE.AmbientLight(0xffffff,0.6));
  var dl=new THREE.DirectionalLight(0xffffff,1.5); dl.position.set(2,4,3); scene.add(dl);
  var fl=new THREE.DirectionalLight(0xffeedd,0.5); fl.position.set(-2,2,-1); scene.add(fl);
  scene.add(new THREE.HemisphereLight(0xffeeb1,0x080820,0.3));
  var loader=new THREE.GLTFLoader();
  loader.load("Assets/Franz Kafka.glb",function(g){var m=g.scene;var b=new THREE.Box3().setFromObject(m);var c=b.getCenter(new THREE.Vector3());var s=b.getSize(new THREE.Vector3());var mx=Math.max(s.x,s.y,s.z);var sc=2/mx;m.scale.setScalar(sc);m.position.sub(c.multiplyScalar(sc));m.position.y+=0.5;scene.add(m);controls.target.set(0,m.position.y+(s.y*sc)/2,0);},undefined,function(e){console.warn("Failed to load model:",e);});
  function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();
  window.addEventListener("resize",function(){var w2=container.clientWidth,h2=container.clientHeight;camera.aspect=w2/h2;camera.updateProjectionMatrix();renderer.setSize(w2,h2);});
})();
