(function() {
  "use strict";

  document.getElementById("booksBtn").addEventListener("click", function() {
    document.getElementById("booksSection").scrollIntoView({ behavior: "smooth" });
  });

  // ===================== READER SYSTEM =====================
  var books = {
    zarathustra: {
      title: "Thus Spoke Zarathustra",
      cover: "Assets/Thus Spoke Zarathustra cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: Zarathustra's Prologue", text: "<p>Zarathustra descends from his mountain cave after ten years of solitude. He has accumulated wisdom and now overflows with it, like a cup that wants to be emptied. He decides to go down to humanity and share what he has learned.</p><p>On his way, he meets an old saint in the forest who spends his days praising God. Zarathustra is amazed: the old saint has not yet heard that God is dead. This declaration — God is dead — is the foundation of everything that follows.</p><p>Zarathustra arrives at a town and addresses the crowd in the marketplace. He tells them about the Übermensch — the overman who will give meaning to the earth. But the crowd laughs and asks instead for the last man, a creature of comfort who has no ambition beyond happiness.</p>" },
        { title: "Chapter 2: The Three Metamorphoses", text: "<p>Zarathustra describes three transformations of the spirit. First, the spirit becomes a camel — it takes on the heaviest burdens, the hardest duties, and bears them into the desert. The camel represents the person who accepts tradition and obligation.</p><p>In the desert, the camel becomes a lion. The lion says 'I will' against the great dragon of 'Thou shalt.' It fights against all imposed values and creates freedom for new creation. But the lion can only destroy — it cannot create new values.</p><p>Finally, the lion becomes a child. The child is innocence and forgetting, a new beginning, a sacred Yes. The child creates new values not from rebellion but from pure affirmation. This is the highest state of the spirit — creative, joyful, and free.</p>" },
        { title: "Chapter 3: On the Despisers of the Body", text: "<p>Zarathustra challenges those who despise the body in favor of the soul. The body is not a prison for the spirit — it is the spirit's instrument and expression. Behind your thoughts and feelings stands a mighty ruler: the Self, which lives in the body.</p><p>The despisers of the body are really despisers of life. They want to escape the earth, to transcend the physical, to find meaning in another world. But Zarathustra insists that meaning must be found here, in this life, on this earth.</p><p>The body's wisdom is deeper than the mind's cleverness. It knows things that consciousness cannot grasp. The healthy person does not despise their body but listens to it, honors it, and uses it as a bridge to higher creation.</p>" },
        { title: "Chapter 4: On the Thousand and One Goals", text: "<p>Every people has created its own table of values — its own definition of good and evil. What one culture praises, another condemns. There is no universal morality, only the values that each people creates to serve its will to power.</p><p>Zarathustra surveys the values of different civilizations. The Greeks valued honor and competition. The Persians valued truthfulness. The Jews valued obedience to God. Each set of values served the survival and flourishing of its people.</p><p>But now humanity needs a new goal — the Übermensch. The old values have lost their power. God is dead, and with him the foundation of traditional morality. Humanity must create new values or perish in nihilism.</p>" },
        { title: "Chapter 5: On the Flies of the Marketplace", text: "<p>Zarathustra warns against the marketplace — the realm of public opinion, fame, and popular approval. The great person must flee the marketplace, for it is filled with poisonous flies: flatterers, critics, and the envious.</p><p>The crowd cannot understand greatness. They measure everything by their own small standards. The creator who seeks approval from the crowd will be corrupted by it. True creation requires solitude and indifference to public opinion.</p><p>Zarathustra advises: flee into your solitude. You have lived too close to the small and the pitiful. Flee from their invisible revenge. They are too small to understand you, so they will try to diminish you. Your best protection is distance.</p>" },
        { title: "Chapter 6: On Self-Overcoming", text: "<p>Zarathustra reveals the secret he has discovered in all living things: the will to power. Life does not merely seek to preserve itself — it seeks to overcome itself, to grow, to become more than it is.</p><p>This will to power is not about domination over others but about self-mastery and self-transcendence. The truly powerful person is not the tyrant but the one who commands themselves, who imposes form on their own chaos.</p><p>Every value, every moral system, every culture is an expression of the will to power. When a value system can no longer promote growth and self-overcoming, it must be replaced. This is the eternal cycle of creation and destruction.</p>" },
        { title: "Chapter 7: On Redemption", text: "<p>Zarathustra encounters cripples and beggars who ask him to heal them. But he warns against removing a person's hump — it might also remove their spirit. The whole person includes their suffering and their limitations.</p><p>The great problem of humanity is the past. We cannot change what has been. The will is powerless against time — it cannot will backwards. This creates resentment: anger at the unchangeable past.</p><p>Redemption comes through the doctrine of eternal recurrence. If we can affirm everything that has happened — every pain, every mistake, every loss — and will it to happen again eternally, then we are redeemed. The past is no longer a prison but a chosen destiny.</p>" },
        { title: "Chapter 8: The Convalescent", text: "<p>Zarathustra falls ill after confronting his most abysmal thought: the eternal recurrence of all things. If everything recurs eternally, then not only the great and beautiful but also the small, the petty, and the ugly will return forever.</p><p>His animals — the eagle and the serpent — nurse him back to health. They tell him that the world is a circle, that everything goes and returns, that the center is everywhere. But Zarathustra knows they are simplifying his deepest insight.</p><p>The eternal recurrence is not just a cosmological theory — it is a test of character. Can you affirm your life so completely that you would want to live it again, exactly as it was, for all eternity? This is the ultimate measure of a life well lived.</p>" },
        { title: "Chapter 9: On the Higher Man", text: "<p>Zarathustra encounters several 'higher men' — individuals who have risen above the herd but have not yet reached the level of the Übermensch. They include a king, a magician, a pope, and the ugliest man.</p><p>These higher men suffer because they are too great for the world they live in but not great enough to create a new world. They are caught between the old values they have outgrown and the new values they cannot yet create.</p><p>Zarathustra invites them to his cave and teaches them to laugh, to dance, and to affirm life. But he warns them: do not follow me. Find your own way. The Übermensch is not a leader to be followed but an ideal to be surpassed.</p>" },
        { title: "Chapter 10: The Sign", text: "<p>Zarathustra wakes on his final morning with a new strength and certainty. His great work is about to begin. The higher men in his cave have been a preparation, but they are not his true companions.</p><p>A lion appears at his cave, surrounded by doves — symbols of pride and gentleness combined. Zarathustra recognizes this as the sign he has been waiting for. His children are near — the new generation that will carry his vision forward.</p><p>The book ends with Zarathustra leaving his cave, glowing and strong like a morning sun. His pity for the higher men has been overcome. He is ready for his final task: not to save humanity but to inspire it to save itself. Thus spoke Zarathustra — and he left his cave, glowing and strong as a morning sun that comes out of dark mountains.</p>" }
      ]
    },
    beyondgoodandevil: {
      title: "Beyond Good and Evil",
      cover: "Assets/Beyond Good and Evil cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: On the Prejudices of Philosophers", text: "<p>Nietzsche opens by questioning the will to truth itself. Why do we want truth? What if untruth is more valuable for life? Philosophers have always assumed that truth is good and falsehood is bad, but this assumption has never been examined.</p><p>Every great philosophy, Nietzsche argues, is a confession of its author — an involuntary memoir. Behind every system of thought lies a personal drive, a hidden desire, a will to power masquerading as a will to truth.</p><p>The most dangerous prejudice of philosophers is their faith in opposite values: good and evil, true and false, selfless and selfish. What if these opposites are not really opposite? What if truth grows out of error, selflessness out of selfishness, reason out of passion?</p>" },
        { title: "Chapter 2: The Free Spirit", text: "<p>Nietzsche describes the free spirit — the thinker who has liberated themselves from all dogmas, traditions, and inherited beliefs. The free spirit does not belong to any party, nation, or creed. They think for themselves.</p><p>But freedom is not easy. The free spirit must endure loneliness, misunderstanding, and the hostility of the herd. Most people prefer the comfort of shared beliefs to the terror of independent thought.</p><p>The free spirit is not a nihilist — they do not reject all values. Rather, they create their own values through experimentation and self-overcoming. They are philosophers of the future, preparing the ground for a new civilization.</p>" },
        { title: "Chapter 3: The Religious Nature", text: "<p>Nietzsche analyzes religion as a tool of power. Christianity, in particular, has been the most effective instrument for controlling the masses. It teaches obedience, humility, and self-denial — virtues that serve the interests of rulers.</p><p>But religion also reveals something profound about human nature: the need for meaning, the fear of suffering, and the desire for transcendence. These needs do not disappear when religion dies — they must be addressed by philosophy.</p><p>Nietzsche does not simply dismiss religion. He recognizes its psychological power and its role in shaping civilization. But he insists that humanity must outgrow it, just as a child outgrows fairy tales, and find new sources of meaning.</p>" },
        { title: "Chapter 4: Epigrams and Interludes", text: "<p>Nietzsche offers a collection of sharp, provocative aphorisms. 'Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss also gazes into you.'</p><p>'The thought of suicide is a great consolation: by means of it one gets through many a dark night.' These aphorisms are not casual observations but compressed philosophical arguments, each one a seed that could grow into an entire book.</p><p>Nietzsche's aphoristic style is deliberate. He distrusts systematic philosophy because systems impose false order on the chaos of reality. The aphorism captures a single insight in its full intensity, without diluting it with qualifications and explanations.</p>" },
        { title: "Chapter 5: On the Natural History of Morals", text: "<p>Nietzsche argues that morality is not universal but historical. Every moral system reflects the conditions under which it arose. What we call 'good' is simply what has been useful for a particular group at a particular time.</p><p>He distinguishes between master morality and slave morality. Master morality values strength, pride, and nobility. Slave morality values humility, compassion, and equality. Christianity is the triumph of slave morality over master morality.</p><p>This is not a simple endorsement of master morality. Nietzsche recognizes that both types have their strengths and weaknesses. But he insists that we must understand the origins of our moral beliefs before we can evaluate them honestly.</p>" },
        { title: "Chapter 6: We Scholars", text: "<p>Nietzsche criticizes the modern scholar — the specialist who knows everything about their narrow field but nothing about life. The scholar is a useful instrument but not a leader. They serve knowledge but do not create values.</p><p>The philosopher of the future must be more than a scholar. They must be a commander and legislator — someone who creates new values and imposes them on the chaos of existence. Knowledge alone is not enough; what matters is the will to shape the future.</p><p>Nietzsche warns against the democratic leveling of intellectual life. Not all opinions are equal. Not all perspectives are valid. The great thinker stands above the crowd, not because they are arrogant but because they see further.</p>" },
        { title: "Chapter 7: Our Virtues", text: "<p>Nietzsche examines the virtues that modern Europeans pride themselves on: honesty, compassion, tolerance, and fairness. He asks whether these virtues are truly virtuous or merely comfortable.</p><p>Honesty, for example, may be the last virtue left to free spirits — the one virtue that survives the death of God. But even honesty must be questioned. Are we honest because we love truth, or because we are too weak to create beautiful lies?</p><p>Compassion, which Christianity elevated to the highest virtue, may actually be a form of weakness. The truly strong person does not need to feel others' pain — they help from a position of abundance, not from shared suffering.</p>" },
        { title: "Chapter 8: Peoples and Fatherlands", text: "<p>Nietzsche analyzes the national characters of European peoples. He sees Europe as a single cultural entity that is being fragmented by nationalism. The future belongs not to nations but to 'good Europeans' who transcend national boundaries.</p><p>He is particularly critical of German nationalism, which he sees as a form of cultural regression. Germany's strength lies not in its military power but in its philosophical and musical traditions — traditions that are universal, not national.</p><p>Nietzsche envisions a united Europe led by a new aristocracy of the spirit — thinkers, artists, and creators who draw on the best of every national tradition to create something greater than any single nation could produce.</p>" },
        { title: "Chapter 9: What Is Noble?", text: "<p>Nietzsche defines nobility not by birth or wealth but by character. The noble person has a fundamental faith in themselves. They do not need external validation. They create their own values and live by them with unwavering commitment.</p><p>The noble person is hard on themselves and gentle with others — not from weakness but from strength. They can afford to be generous because they have an abundance of power. They do not resent those who are different — they simply do not compare themselves.</p><p>Nobility requires solitude. The noble person must spend time alone, away from the crowd, cultivating their inner life. They must resist the temptation to conform, to seek approval, to sacrifice their uniqueness for the comfort of belonging.</p>" },
        { title: "Chapter 10: From High Mountains", text: "<p>Nietzsche concludes with a poem — an afterword that expresses in verse what the preceding chapters argued in prose. He speaks of waiting on high mountains for friends who never come, of the loneliness of the thinker who sees too far ahead.</p><p>The philosopher of the future is a solitary figure, misunderstood by their contemporaries, appreciated only by those who come after. They plant seeds that will not bear fruit in their lifetime. Their reward is not fame but the knowledge that they have served the future.</p><p>Beyond Good and Evil ends with a challenge: the old morality is dying, and a new one must be born. Who will create it? Not the scholars, not the priests, not the politicians — but the philosophers of the future, the free spirits who dare to think beyond the categories of good and evil.</p>" }
      ]
    }
  };

  var currentBook = null, currentPage = 0;

  function openBook(k) { currentBook = books[k]; if (!currentBook) return; currentPage = 0; document.getElementById("readerOverlay").classList.add("active"); document.body.style.overflow = "hidden"; renderPage(); }
  function closeBook() { document.getElementById("readerOverlay").classList.remove("active"); document.body.style.overflow = ""; currentBook = null; }
  function renderPage() {
    if (!currentBook) return;
    var ch = currentBook.chapters[currentPage], ci = document.getElementById("readerCoverImg"), ce = document.getElementById("readerChapter"), ti = document.getElementById("chapterTitle"), te = document.getElementById("chapterText"), ind = document.getElementById("readerIndicator"), rt = document.getElementById("readerTitle"), pb = document.getElementById("readerPrev"), nb = document.getElementById("readerNext");
    if (ch.type === "cover") { ci.style.display="block"; ci.src=currentBook.cover; ce.classList.remove("visible"); rt.textContent=currentBook.title; }
    else { ci.style.display="none"; ce.classList.add("visible"); ti.textContent=ch.title; te.innerHTML=ch.text; rt.textContent=ch.title; ce.scrollTop=0; }
    ind.textContent=(currentPage+1)+" / "+currentBook.chapters.length; pb.disabled=currentPage===0; nb.disabled=currentPage===currentBook.chapters.length-1;
  }

  document.querySelectorAll(".book-read-btn").forEach(function(b){b.addEventListener("click",function(){openBook(b.dataset.book);});});
  document.getElementById("readerBackBtn").addEventListener("click",closeBook);
  document.getElementById("readerPrev").addEventListener("click",function(){if(currentBook&&currentPage>0){currentPage--;renderPage();}});
  document.getElementById("readerNext").addEventListener("click",function(){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}});
  document.addEventListener("keydown",function(e){if(!document.getElementById("readerOverlay").classList.contains("active"))return;if(e.key==="ArrowRight"){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}}else if(e.key==="ArrowLeft"){if(currentBook&&currentPage>0){currentPage--;renderPage();}}else if(e.key==="Escape"){closeBook();}});
  var scrollCD=false;document.getElementById("readerOverlay").addEventListener("wheel",function(e){if(!currentBook||scrollCD)return;var ce=document.getElementById("readerChapter");if(currentPage===0||!ce.classList.contains("visible")){e.preventDefault();scrollCD=true;if(e.deltaY>0&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}else if(e.deltaY<0&&currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);return;}var aT=ce.scrollTop<=0,aB=ce.scrollTop+ce.clientHeight>=ce.scrollHeight-5;if(aB&&e.deltaY>0){e.preventDefault();scrollCD=true;if(currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}setTimeout(function(){scrollCD=false;},200);}else if(aT&&e.deltaY<0){e.preventDefault();scrollCD=true;if(currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);}},{passive:false});

  // ===================== 3D MODEL =====================
  var container = document.getElementById("modelContainer");
  var w = container.clientWidth, h = container.clientHeight;
  var scene = new THREE.Scene();
  var camera = new THREE.PerspectiveCamera(45, w/h, 0.01, 100);
  camera.position.set(0, 1, 3);
  var renderer = new THREE.WebGLRenderer({ antialias:true, alpha:true });
  renderer.setClearColor(0x000000, 0);
  renderer.setSize(w, h);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  container.appendChild(renderer.domElement);
  var controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping=true; controls.dampingFactor=0.05; controls.autoRotate=true; controls.autoRotateSpeed=2; controls.enableZoom=false; controls.target.set(0,0.8,0);
  scene.add(new THREE.AmbientLight(0xffffff,0.6));
  var dl=new THREE.DirectionalLight(0xffffff,1.5); dl.position.set(2,4,3); scene.add(dl);
  var fl=new THREE.DirectionalLight(0xffeedd,0.5); fl.position.set(-2,2,-1); scene.add(fl);
  scene.add(new THREE.HemisphereLight(0xffeeb1,0x080820,0.3));
  var loader=new THREE.GLTFLoader();
  loader.load("Assets/Friedrich Nietzsche.glb",function(g){var m=g.scene;var b=new THREE.Box3().setFromObject(m);var c=b.getCenter(new THREE.Vector3());var s=b.getSize(new THREE.Vector3());var mx=Math.max(s.x,s.y,s.z);var sc=2/mx;m.scale.setScalar(sc);m.position.sub(c.multiplyScalar(sc));m.position.y+=0.5;scene.add(m);controls.target.set(0,m.position.y+(s.y*sc)/2,0);},undefined,function(e){console.warn("Failed to load model:",e);});
  function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();
  window.addEventListener("resize",function(){var w2=container.clientWidth,h2=container.clientHeight;camera.aspect=w2/h2;camera.updateProjectionMatrix();renderer.setSize(w2,h2);});
})();
