(function() {
  "use strict";

  document.getElementById("booksBtn").addEventListener("click", function() {
    document.getElementById("booksSection").scrollIntoView({ behavior: "smooth" });
  });

  // ===================== READER SYSTEM =====================
  var books = {
    letters: {
      title: "Letters from a Stoic",
      cover: "Assets/Letters from a Stoic cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: On Saving Time", text: "<p>Seneca opens his letters to Lucilius with the most urgent advice: guard your time. Nothing belongs to us except time, yet we squander it as if it were infinite. We are careful with money but reckless with the hours of our lives.</p><p>People give away their time to anyone who asks — to social obligations, to trivial amusements, to worry about the future. They would never hand over their money so freely, yet time is the one thing that can never be recovered.</p><p>Seneca urges Lucilius to reclaim his time. Withdraw from pointless engagements. Dedicate each day to self-improvement. Live as if each day were your last, not in panic, but with the focused attention of someone who knows the value of what they hold.</p>" },
        { title: "Chapter 2: On the Terrors of Death", text: "<p>Most people spend their lives fearing death, yet they waste the very life they are trying to protect. The fear of death is worse than death itself. We suffer more in anticipation than in reality.</p><p>Seneca argues that death is neither good nor evil — it is simply the end of sensation. Before we were born, we did not exist, and we did not suffer. Death returns us to that same state. There is nothing to fear in non-existence.</p><p>The wise person does not cling to life or flee from death. They accept both with equanimity. What matters is not how long we live but how well. A short life lived with virtue is worth more than a long life wasted in anxiety.</p>" },
        { title: "Chapter 3: On True Friendship", text: "<p>Seneca distinguishes between true friendship and the shallow connections most people call friendship. True friends share everything — their thoughts, their fears, their hopes. There is complete trust between them.</p><p>Before making someone a friend, judge their character carefully. But once you have accepted them, trust them completely. The person who trusts no one is as foolish as the person who trusts everyone.</p><p>A true friend is another self. They rejoice in your success without envy and share your sorrows without complaint. Such friendships are rare and precious — they are among the greatest goods that life offers.</p>" },
        { title: "Chapter 4: On the Philosopher's Seclusion", text: "<p>Seneca advises a balance between solitude and society. Too much solitude breeds misanthropy; too much society breeds superficiality. The wise person alternates between the two, refreshing themselves in solitude and testing themselves in company.</p><p>In solitude, we study, reflect, and strengthen our principles. In society, we practice what we have learned. The crowd can corrupt us if we are not careful — it is easy to adopt the values of those around us.</p><p>Choose your companions wisely. Associate with those who will make you better, and whom you can make better in return. Avoid the company of those who complain constantly, who indulge in excess, or who value appearance over substance.</p>" },
        { title: "Chapter 5: On the Happy Life", text: "<p>Happiness does not depend on external circumstances. The happy person is not the one who has the most but the one who needs the least. Wealth, fame, and pleasure are not evil, but they are not the source of lasting happiness.</p><p>True happiness comes from living in accordance with nature and reason. It comes from virtue — from being just, courageous, temperate, and wise. These qualities are within our control, unlike fortune's gifts.</p><p>Seneca acknowledges that he himself is wealthy and has enjoyed the pleasures of Roman high society. He does not condemn wealth but warns against depending on it. Use fortune's gifts when they come, but do not grieve when they depart.</p>" },
        { title: "Chapter 6: On Grief and Consolation", text: "<p>Seneca writes with deep compassion about grief. He does not dismiss sorrow as weakness — he acknowledges that losing someone we love is genuinely painful. But he argues that excessive grief dishonors the dead and harms the living.</p><p>The person who grieves without end is not showing love but self-pity. They are mourning not for the dead but for themselves. The dead are beyond suffering; it is the living who need consolation.</p><p>Seneca advises moderation in grief. Weep, but not forever. Remember the good times with gratitude rather than dwelling on the loss with bitterness. The best way to honor the dead is to live well in their memory.</p>" },
        { title: "Chapter 7: On the Value of Philosophy", text: "<p>Philosophy is not an academic exercise but a practical art of living. It teaches us how to face adversity, how to enjoy prosperity without corruption, and how to die with dignity.</p><p>Seneca criticizes philosophers who waste time on logical puzzles and verbal tricks while ignoring the urgent questions of how to live. What good is it to know whether the number of stars is odd or even if you cannot control your own anger?</p><p>The value of philosophy is measured by its effect on character. A good philosophy makes you braver, more patient, more generous, and more honest. If your philosophy does not change how you live, it is worthless.</p>" },
        { title: "Chapter 8: On Anger and Patience", text: "<p>Anger is the most destructive of all emotions. It clouds judgment, destroys relationships, and leads to actions we later regret. No decision made in anger is a good decision.</p><p>Seneca recommends a simple technique: when you feel anger rising, delay. Do not speak or act until the initial surge has passed. Most anger fades quickly if we do not feed it with rumination.</p><p>The patient person is not weak but strong. It takes more strength to restrain anger than to express it. The person who can remain calm in the face of provocation has achieved a victory greater than any military conquest.</p>" },
        { title: "Chapter 9: On Providence and Adversity", text: "<p>Why do bad things happen to good people? Seneca answers that adversity is not punishment but training. The gods test those they love, just as a good teacher challenges their best students.</p><p>A life without difficulty produces a weak character. Comfort and ease are the enemies of growth. The person who has never faced hardship has never discovered their own strength.</p><p>Seneca points to examples of great men who endured terrible suffering — Socrates, Cato, Regulus. Their greatness was not diminished by their suffering but revealed by it. Adversity is the fire that forges the strongest steel.</p>" },
        { title: "Chapter 10: On the Shortness of Life", text: "<p>Life is long enough if we use it well. The problem is not that we have too little time but that we waste too much of it. We are prodigal with the one thing we cannot afford to lose.</p><p>Seneca catalogs the ways we waste time: in pointless ambition, in social climbing, in worry about the future, in regret about the past. We postpone living, always preparing for a tomorrow that may never come.</p><p>The wise person lives in the present. They do not anxiously await the future or cling to the past. Each day is a complete life in miniature. If you can say at the end of each day, 'I have lived,' then you have not wasted your time on earth.</p>" }
      ]
    },
    shortness: {
      title: "On the Shortness of Life",
      cover: "Assets/On the Shortness of Life cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: Life Is Long Enough", text: "<p>Seneca addresses Paulinus with a provocative claim: life is not short — we make it short. We receive a generous allotment of time, but we waste most of it on trivial pursuits, leaving us feeling that life has passed us by.</p><p>The majority of mortals complain about the meanness of nature — that we are born for so brief a span. But it is not that we have a short time to live, but that we squander a great deal of it.</p><p>Life is long if you know how to use it. But when it is wasted in luxury and carelessness, when it is devoted to no good purpose, we are forced at last by death's final constraint to realize that it has passed away before we knew it was passing.</p>" },
        { title: "Chapter 2: How We Waste Our Lives", text: "<p>Seneca catalogs the ways people waste their lives. Some are consumed by greed, always chasing more wealth. Others are consumed by ambition, spending years pursuing political office. Still others waste their time in idle luxury, eating, drinking, and sleeping their lives away.</p><p>Even those who seem busy are often wasting time. The person who spends all day managing their investments, attending social functions, or pursuing legal cases may be occupied, but they are not truly living.</p><p>The busiest people are often the most impoverished in terms of real living. They have no time for reflection, for friendship, for the cultivation of wisdom. They are slaves to their schedules, not masters of their time.</p>" },
        { title: "Chapter 3: The Preoccupied Mind", text: "<p>The preoccupied person — the one always busy with external affairs — never has time for themselves. They are always preparing to live but never actually living. Their entire existence is spent in anticipation of a future that never arrives.</p><p>They say: 'After I finish this project, I will relax. After I retire, I will enjoy life. After I achieve this goal, I will be happy.' But the finish line keeps moving. There is always one more thing to do before they can begin to live.</p><p>Seneca warns that this postponement of life is the greatest waste of all. The future is uncertain — we may not live to see tomorrow. The only time we truly possess is the present moment, and we must use it wisely.</p>" },
        { title: "Chapter 4: The Value of the Past", text: "<p>Of the three divisions of time — past, present, and future — only the past is secure. The present is fleeting, and the future is uncertain. But the past belongs to us forever, beyond the reach of fortune.</p><p>The wise person reviews their past with satisfaction, recalling days well spent and lessons learned. The foolish person avoids looking back because their past is filled with regret and wasted opportunities.</p><p>Seneca argues that the person who has lived well has a rich store of memories to draw upon. Their past is a source of strength and comfort. But the person who has wasted their life dreads looking back — their past is a wasteland of missed chances.</p>" },
        { title: "Chapter 5: Slavery to Others", text: "<p>Many people give away their time to others without a second thought. They attend every social gathering, fulfill every obligation, and respond to every request. They are generous with the one thing they should guard most jealously.</p><p>If someone asked for your money, you would refuse or at least hesitate. But when someone asks for your time — which is far more valuable — you give it freely. You would never let someone steal your property, yet you let everyone steal your hours.</p><p>Seneca urges us to be miserly with our time. Say no to unnecessary commitments. Guard your hours as you would guard your gold. The person who gives away all their time has nothing left for themselves.</p>" },
        { title: "Chapter 6: The Illusion of Retirement", text: "<p>Many people plan to begin living after they retire. They endure decades of drudgery, promising themselves that freedom awaits at the end. But retirement often comes too late — the body is worn out, the mind is dulled, and the energy for living has been spent.</p><p>Even those who do retire often find themselves at a loss. They have spent so long being busy that they do not know how to be at leisure. They fill their retirement with the same trivial pursuits that consumed their working years.</p><p>Seneca argues that we should not postpone living until retirement. Every day should contain some element of genuine life — reflection, learning, meaningful conversation, and the cultivation of virtue. Do not wait for permission to live.</p>" },
        { title: "Chapter 7: The Philosopher's Use of Time", text: "<p>The philosopher alone knows how to use time well. While others waste their hours on ambition, pleasure, and worry, the philosopher devotes their time to the pursuit of wisdom and the cultivation of virtue.</p><p>The philosopher's life is the longest of all because they add the wisdom of all past ages to their own experience. Through reading and reflection, they live not just their own life but the lives of Socrates, Plato, Zeno, and all the great thinkers who came before.</p><p>This is the true extension of life — not adding years to our span but adding depth to our experience. The philosopher who lives fifty years with wisdom has lived longer than the fool who lives a hundred years in ignorance.</p>" },
        { title: "Chapter 8: The Crowd and Its Distractions", text: "<p>The crowd is the enemy of the thoughtful life. It pulls us into its concerns, its entertainments, and its values. Before we know it, we have adopted the crowd's priorities and abandoned our own.</p><p>Seneca describes the Roman spectacles — the gladiatorial games, the chariot races, the theatrical performances — as massive wastes of time. People spend entire days watching others live while their own lives slip away.</p><p>The wise person limits their exposure to the crowd. They choose their entertainments carefully, preferring activities that nourish the mind over those that merely stimulate the senses. They are selective about how they spend their leisure.</p>" },
        { title: "Chapter 9: Great Men and Their Regrets", text: "<p>Seneca cites examples of powerful men who, at the end of their lives, regretted how they had spent their time. Augustus Caesar longed for leisure. Cicero complained of being trapped by his own success. Even the most powerful people feel the sting of wasted time.</p><p>Power and fame do not protect us from the passage of time. The emperor and the slave both receive the same allotment of hours. The difference is that the emperor's hours are consumed by the demands of others, while the slave may at least have moments of genuine freedom.</p><p>These examples show that external success is no guarantee of a well-lived life. The person who achieves everything the world values may still arrive at death feeling that they never truly lived.</p>" },
        { title: "Chapter 10: Seize the Day", text: "<p>Seneca concludes with an urgent call to action. Do not wait for the perfect moment to begin living — it will never come. Start now. This very day, reclaim your time from the thieves who would steal it.</p><p>Withdraw from unnecessary obligations. Simplify your life. Devote your best hours to philosophy, friendship, and self-improvement. These are the activities that give life meaning and substance.</p><p>The person who lives each day as if it were their last — not in panic but in purposeful attention — will never feel that life was too short. They will arrive at death satisfied, having used their time well. As Seneca writes: 'It is not that we have a short time to live, but that we waste a great deal of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested.'</p>" }
      ]
    }
  };

  var currentBook = null, currentPage = 0;

  function openBook(k) { currentBook = books[k]; if (!currentBook) return; currentPage = 0; document.getElementById("readerOverlay").classList.add("active"); document.body.style.overflow = "hidden"; renderPage(); }
  function closeBook() { document.getElementById("readerOverlay").classList.remove("active"); document.body.style.overflow = ""; currentBook = null; }
  function renderPage() {
    if (!currentBook) return;
    var ch = currentBook.chapters[currentPage], ci = document.getElementById("readerCoverImg"), ce = document.getElementById("readerChapter"), ti = document.getElementById("chapterTitle"), te = document.getElementById("chapterText"), ind = document.getElementById("readerIndicator"), rt = document.getElementById("readerTitle"), pb = document.getElementById("readerPrev"), nb = document.getElementById("readerNext");
    if (ch.type === "cover") { ci.style.display="block"; ci.src=currentBook.cover; ce.classList.remove("visible"); rt.textContent=currentBook.title; }
    else { ci.style.display="none"; ce.classList.add("visible"); ti.textContent=ch.title; te.innerHTML=ch.text; rt.textContent=ch.title; ce.scrollTop=0; }
    ind.textContent=(currentPage+1)+" / "+currentBook.chapters.length; pb.disabled=currentPage===0; nb.disabled=currentPage===currentBook.chapters.length-1;
  }

  document.querySelectorAll(".book-read-btn").forEach(function(b){b.addEventListener("click",function(){openBook(b.dataset.book);});});
  document.getElementById("readerBackBtn").addEventListener("click",closeBook);
  document.getElementById("readerPrev").addEventListener("click",function(){if(currentBook&&currentPage>0){currentPage--;renderPage();}});
  document.getElementById("readerNext").addEventListener("click",function(){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}});
  document.addEventListener("keydown",function(e){if(!document.getElementById("readerOverlay").classList.contains("active"))return;if(e.key==="ArrowRight"){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}}else if(e.key==="ArrowLeft"){if(currentBook&&currentPage>0){currentPage--;renderPage();}}else if(e.key==="Escape"){closeBook();}});
  var scrollCD=false;document.getElementById("readerOverlay").addEventListener("wheel",function(e){if(!currentBook||scrollCD)return;var ce=document.getElementById("readerChapter");if(currentPage===0||!ce.classList.contains("visible")){e.preventDefault();scrollCD=true;if(e.deltaY>0&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}else if(e.deltaY<0&&currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);return;}var aT=ce.scrollTop<=0,aB=ce.scrollTop+ce.clientHeight>=ce.scrollHeight-5;if(aB&&e.deltaY>0){e.preventDefault();scrollCD=true;if(currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}setTimeout(function(){scrollCD=false;},200);}else if(aT&&e.deltaY<0){e.preventDefault();scrollCD=true;if(currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);}},{passive:false});

  // ===================== 3D MODEL =====================
  var container = document.getElementById("modelContainer");
  var w = container.clientWidth, h = container.clientHeight;
  var scene = new THREE.Scene();
  var camera = new THREE.PerspectiveCamera(45, w/h, 0.01, 100);
  camera.position.set(0, 1, 3);
  var renderer = new THREE.WebGLRenderer({ antialias:true, alpha:true });
  renderer.setClearColor(0x000000, 0);
  renderer.setSize(w, h);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  container.appendChild(renderer.domElement);
  var controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping=true; controls.dampingFactor=0.05; controls.autoRotate=true; controls.autoRotateSpeed=2; controls.enableZoom=false; controls.target.set(0,0.8,0);
  scene.add(new THREE.AmbientLight(0xffffff,0.6));
  var dl=new THREE.DirectionalLight(0xffffff,1.5); dl.position.set(2,4,3); scene.add(dl);
  var fl=new THREE.DirectionalLight(0xffeedd,0.5); fl.position.set(-2,2,-1); scene.add(fl);
  scene.add(new THREE.HemisphereLight(0xffeeb1,0x080820,0.3));
  var loader=new THREE.GLTFLoader();
  loader.load("Assets/seneca.glb",function(g){var m=g.scene;var b=new THREE.Box3().setFromObject(m);var c=b.getCenter(new THREE.Vector3());var s=b.getSize(new THREE.Vector3());var mx=Math.max(s.x,s.y,s.z);var sc=2/mx;m.scale.setScalar(sc);m.position.sub(c.multiplyScalar(sc));m.position.y+=0.5;scene.add(m);controls.target.set(0,m.position.y+(s.y*sc)/2,0);},undefined,function(e){console.warn("Failed to load model:",e);});
  function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();
  window.addEventListener("resize",function(){var w2=container.clientWidth,h2=container.clientHeight;camera.aspect=w2/h2;camera.updateProjectionMatrix();renderer.setSize(w2,h2);});
})();
