(function() {
  "use strict";

  document.getElementById("booksBtn").addEventListener("click", function() {
    document.getElementById("booksSection").scrollIntoView({ behavior: "smooth" });
  });

  // ===================== READER SYSTEM =====================
  var books = {
    apology: {
      title: "Apology",
      cover: "Assets/Apology cover .jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: The Charges Against Socrates", text: "<p>Socrates stands before the Athenian jury to defend himself against charges of impiety and corrupting the youth. He begins by warning the jurors that he will speak plainly, not with the polished rhetoric of his accusers.</p><p>He addresses the old prejudices against him first — the rumors spread over many years that he is a natural philosopher who studies the heavens and makes the weaker argument stronger. These informal accusations, he argues, are more dangerous than the formal charges.</p><p>Socrates traces these misunderstandings to the comedies of Aristophanes, who portrayed him as a ridiculous figure suspended in a basket studying the clouds. He insists he has no expertise in natural science and has never charged fees for teaching.</p>" },
        { title: "Chapter 2: The Oracle at Delphi", text: "<p>Socrates recounts how his friend Chaerephon visited the Oracle at Delphi and asked whether anyone was wiser than Socrates. The Oracle replied that no one was wiser. This puzzled Socrates, who believed he knew nothing of great importance.</p><p>To test the Oracle's claim, Socrates began questioning those reputed to be wise — politicians, poets, and craftsmen. He discovered that each group believed they possessed wisdom but could not withstand his questioning.</p><p>Socrates concluded that he was wiser only in one respect: he knew that he did not know, while others falsely believed they did. This mission of examining others, he claims, was given to him by the god.</p>" },
        { title: "Chapter 3: Socrates the Gadfly", text: "<p>Socrates compares himself to a gadfly attached to the great horse of Athens — a sluggish animal that needs to be stung into action. Without his constant questioning, the city would fall into intellectual complacency.</p><p>He explains that his poverty is proof of his sincerity. If he were a sophist seeking profit, he would have accumulated wealth. Instead, he has neglected his own affairs to serve the god's mission of philosophical inquiry.</p><p>Socrates acknowledges that his questioning has made him many enemies. Powerful men do not enjoy being shown that their wisdom is hollow. But he cannot abandon his mission without disobeying the divine command.</p>" },
        { title: "Chapter 4: Cross-Examination of Meletus", text: "<p>Socrates turns to cross-examine his chief accuser, Meletus. He asks who improves the youth if Socrates corrupts them. Meletus claims the laws, the jurors, and all Athenians improve the youth — everyone except Socrates.</p><p>Socrates exposes the absurdity of this claim through analogy. In horse training, only a few experts improve horses while the majority harm them. The same principle applies to moral education — it is unlikely that one man alone corrupts while everyone else improves.</p><p>He then challenges the charge of impiety. Meletus accuses Socrates of being a complete atheist, yet the original charge states he introduces new divine beings. Socrates shows these claims contradict each other, revealing that Meletus has not thought carefully about his accusations.</p>" },
        { title: "Chapter 5: The Examined Life", text: "<p>Socrates declares his most famous principle: the unexamined life is not worth living. He would rather die than give up philosophy. Even if the jury offered to acquit him on the condition that he stop philosophizing, he would refuse.</p><p>He explains that he must obey the god rather than the jury. His divine mission requires him to continue examining himself and others, urging everyone to care for wisdom and truth above wealth and reputation.</p><p>Socrates argues that no one should fear death, since we do not know whether it is good or bad. What we do know is that abandoning virtue and truth is harmful. Therefore, the rational choice is to continue living philosophically regardless of the consequences.</p>" },
        { title: "Chapter 6: The Divine Sign", text: "<p>Socrates describes his daimonion — a divine voice or sign that has accompanied him since childhood. This inner voice never tells him what to do but always warns him when he is about to make a mistake.</p><p>He notes that the divine sign did not oppose him when he came to court or during his speech. This suggests that what is happening to him may not be a bad thing. The sign's silence is itself a form of guidance.</p><p>This personal spiritual experience is central to understanding Socrates. He is not an atheist but someone with an unconventional relationship to the divine — one based on inner experience rather than traditional ritual.</p>" },
        { title: "Chapter 7: Why Socrates Avoided Politics", text: "<p>Socrates explains why he never entered public political life. His divine sign warned him against it. He believes that anyone who genuinely fights for justice in Athens would be killed before accomplishing anything.</p><p>He offers two examples from his own life. Under the democracy, he alone opposed the illegal trial of the generals after the battle of Arginusae. Under the oligarchy of the Thirty Tyrants, he refused an order to arrest an innocent man.</p><p>Both times he risked death by standing for justice. These experiences confirmed that a just person cannot survive long in Athenian politics. Instead, Socrates chose to serve the city through private philosophical conversations.</p>" },
        { title: "Chapter 8: Socrates' Poverty and Witnesses", text: "<p>Socrates points to his poverty as evidence that he has never been a paid teacher. He has never charged anyone for conversation. Rich and poor alike are welcome to listen to his questioning.</p><p>He calls attention to the many young men present in the courtroom — former associates and their families — who could testify against him if he had truly corrupted them. None of them have come forward as accusers.</p><p>Socrates refuses to bring his family before the jury to weep and beg for mercy, as is customary. Such emotional appeals, he argues, are beneath the dignity of a man who claims to be wise. The jury should judge based on truth, not pity.</p>" },
        { title: "Chapter 9: The Verdict and Counter-Penalty", text: "<p>The jury finds Socrates guilty by a narrow margin. He is not surprised. In fact, he is amazed that the vote was so close. He expected a much larger majority against him.</p><p>When asked to propose a counter-penalty, Socrates provocatively suggests that he deserves free meals at the Prytaneum — the honor given to Olympic victors and public benefactors. He argues that his service to Athens is worth more than any athletic victory.</p><p>He considers and rejects exile as a penalty. An old man who cannot keep quiet in Athens will certainly cause trouble in any other city. He briefly considers a fine but settles on a modest amount that his friends offer to guarantee.</p>" },
        { title: "Chapter 10: Socrates' Final Words", text: "<p>After being sentenced to death, Socrates addresses the jury one final time. To those who voted to condemn him, he offers a prophecy: his death will not silence philosophical questioning. Younger and harsher critics will take his place.</p><p>To those who voted to acquit him, he offers comfort. Death is either a dreamless sleep — which would be a wonderful gain — or a journey to another place where he can continue questioning the heroes of old. Either way, it is nothing to fear.</p><p>Socrates closes with his famous words: no evil can happen to a good man, either in life or after death. He bears no grudge against his accusers or his judges. He asks only that they treat his sons as he treated the Athenians — by reproaching them if they value wealth over virtue.</p>" }
      ]
    },
    crito: {
      title: "Crito",
      cover: "Assets/crito cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: Crito's Visit at Dawn", text: "<p>Crito arrives at Socrates' prison cell before dawn. He has bribed the guard to let him in early. He watches Socrates sleeping peacefully and marvels at his calm in the face of death.</p><p>When Socrates wakes, Crito tells him that the ship from Delos is expected to arrive soon, which means his execution is imminent. Socrates recounts a dream in which a beautiful woman told him he would arrive in Phthia on the third day — suggesting he has a little more time.</p><p>Crito is desperate. He has come not just to visit but to persuade Socrates to escape. Everything has been arranged — the guards can be bribed, friends in Thessaly will shelter him, and the money is ready.</p>" },
        { title: "Chapter 2: Crito's Arguments for Escape", text: "<p>Crito presents several arguments for why Socrates should escape. First, he will lose a dear friend — a loss that cannot be replaced. People will think Crito valued money over friendship.</p><p>Second, Socrates has a duty to his children. By choosing death, he abandons them to grow up as orphans. A father should not desert his children when he has the power to raise and educate them.</p><p>Third, Socrates' death will look like cowardice — as if he and his friends lacked the courage to save him. Public opinion matters, Crito argues, because the many can inflict great harm.</p>" },
        { title: "Chapter 3: Socrates Questions Public Opinion", text: "<p>Socrates begins his response by questioning whether the opinion of the many should matter. He draws an analogy to physical training: a gymnast follows the advice of his trainer, not the crowd. Similarly, in matters of justice, we should follow the expert, not popular opinion.</p><p>The relevant question is not what people will think but what is right. If escaping is unjust, then Socrates must not escape, regardless of the consequences. The opinion of the many cannot make a bad action good.</p><p>Socrates establishes a crucial principle: it is never right to do wrong, even in retaliation. One must not return injustice for injustice or harm for harm. This principle will guide the rest of the argument.</p>" },
        { title: "Chapter 4: The Social Contract", text: "<p>Socrates introduces a thought experiment. He imagines the Laws of Athens coming to speak with him. The Laws argue that by living in Athens for seventy years, Socrates has implicitly agreed to abide by them.</p><p>The Laws gave Socrates his education, his marriage, and his citizenship. They are like parents to him. A citizen who disagrees with a law has three options: persuade the city to change it, obey it, or leave. Socrates chose to stay.</p><p>By remaining in Athens and enjoying its benefits, Socrates entered into an agreement to follow its laws. Escaping now would break that agreement and undermine the entire legal system.</p>" },
        { title: "Chapter 5: The Laws Speak", text: "<p>The personified Laws continue their argument. If Socrates escapes, he will destroy the authority of law itself. A city cannot survive if its legal judgments have no force and can be overturned by private citizens.</p><p>The Laws remind Socrates that his quarrel is not with them but with the men who misapplied them. The laws themselves are just; it was the jury that made an error. Destroying the laws to escape an unjust verdict would be like burning down a house because one room is damaged.</p><p>The Laws ask Socrates to consider what kind of example he would set. If the greatest philosopher in Athens flees from the law, what message does that send to every citizen who faces an unfavorable judgment?</p>" },
        { title: "Chapter 6: The Consequences of Escape", text: "<p>The Laws describe what would happen if Socrates escaped to a well-governed city like Thebes or Megara. He would arrive as an enemy of law and order. No decent person would trust a man who undermined his own city's legal system.</p><p>If he went to Thessaly, a lawless region, he might find temporary refuge. But he would live as a fugitive, dependent on others, unable to practice philosophy with any credibility. His conversations about justice and virtue would ring hollow.</p><p>Even his children would not benefit. If his friends are willing to care for them after his death, they would do the same if he went into exile. His presence in Thessaly would not improve their upbringing.</p>" },
        { title: "Chapter 7: Justice Over Self-Preservation", text: "<p>Socrates returns to his fundamental principle: one must never do wrong willingly. Even if the verdict against him was unjust, escaping would be a wrong action. Two wrongs do not make a right.</p><p>He distinguishes between suffering injustice and committing injustice. It is better to suffer wrong than to do wrong. The person who commits injustice harms their own soul, which is worse than any physical punishment.</p><p>This is the heart of Socratic ethics. The soul is more important than the body. Protecting the soul from corruption matters more than preserving physical life. Escape would save his body but damage his soul.</p>" },
        { title: "Chapter 8: The Afterlife Argument", text: "<p>The Laws conclude by reminding Socrates of the afterlife. If there is judgment after death, how will he face the laws of the underworld? He will arrive having tried to destroy the laws of his own city.</p><p>But if he accepts his sentence with dignity, he will arrive in the next world as a victim of injustice committed by men, not by laws. The rulers of the underworld will look favorably upon him.</p><p>Socrates tells Crito that these arguments ring in his ears like the music of the Corybantes, drowning out all other considerations. He cannot hear any counter-argument that would be strong enough to overcome them.</p>" },
        { title: "Chapter 9: Crito's Acceptance", text: "<p>Crito admits that he has no further arguments to offer. Socrates' reasoning has been thorough and consistent. The principle that one must never do wrong, even in response to wrong, leaves no room for escape.</p><p>Socrates asks Crito directly: can you refute these arguments? Crito confesses that he cannot. The emotional appeal of saving a friend's life cannot overcome the rational argument for justice.</p><p>This moment reveals the power of Socratic dialogue. Through patient questioning and reasoning, Socrates has transformed Crito's passionate plea into a philosophical acceptance of what must be done.</p>" },
        { title: "Chapter 10: Let Us Follow the God", text: "<p>Socrates concludes with his characteristic calm. He tells Crito to let the matter rest. They should follow the path that the god indicates. There is no point in further deliberation.</p><p>The dialogue ends simply and quietly. There are no dramatic gestures or emotional outbursts. Socrates has made his decision through reason, and he is at peace with it.</p><p>The Crito stands as one of the most powerful arguments for the rule of law and the obligations of citizenship ever written. It shows that Socrates practiced what he preached — he chose justice over self-preservation, principle over comfort, and the examined life over mere survival.</p>" }
      ]
    },
    phaedo: {
      title: "Phaedo",
      cover: "Assets/phaedo cover.jpeg",
      chapters: [
        { title: "Cover", text: "", type: "cover" },
        { title: "Chapter 1: The Last Day of Socrates", text: "<p>Phaedo narrates the events of Socrates' final day to his friend Echecrates. The friends gather at the prison at dawn. Socrates' wife Xanthippe is there with their youngest child, weeping. Socrates asks Crito to have someone take her home.</p><p>Socrates sits up on his bed, rubbing his leg where the chains had been. He reflects on the strange connection between pleasure and pain — how relief from pain brings pleasure. This casual observation sets the philosophical tone for the day.</p><p>The friends are struck by Socrates' serenity. He shows no fear of death. Instead, he seems almost eager to discuss what lies ahead. This calmness will be the subject of the entire dialogue.</p>" },
        { title: "Chapter 2: Philosophy as Preparation for Death", text: "<p>Socrates argues that true philosophers spend their entire lives preparing for death. Philosophy is the practice of separating the soul from the body. Death is simply the completion of this process.</p><p>The body is an obstacle to knowledge. Our senses deceive us, our appetites distract us, and our physical needs consume our time. The philosopher seeks to minimize the body's influence and live as much as possible through pure thought.</p><p>If the philosopher has spent a lifetime training the soul to be independent of the body, then death — the final separation — should be welcomed, not feared. To fear death would be inconsistent with the philosophical life.</p>" },
        { title: "Chapter 3: The Argument from Opposites", text: "<p>Socrates presents his first argument for the immortality of the soul. Everything comes into being from its opposite: the hot from the cold, the sleeping from the waking, the living from the dead.</p><p>If the living come from the dead, then the dead must come from the living. There must be a cycle of birth and death, with souls passing between the two states. Otherwise, everything would eventually end up dead.</p><p>This cyclical argument suggests that death is not an end but a transition. The soul exists before birth and continues after death, moving through an eternal cycle of life and death.</p>" },
        { title: "Chapter 4: The Theory of Recollection", text: "<p>Socrates argues that learning is actually recollection. When we encounter equal sticks or stones, we recognize that they fall short of perfect Equality. But we could not recognize this deficiency unless we already knew what perfect Equality was.</p><p>Since we never encounter perfect Equality in the physical world, we must have known it before birth. Our souls must have existed before we were born and possessed knowledge of the Forms.</p><p>This argument connects the immortality of the soul to Plato's Theory of Forms. The soul's pre-existence is proven by its innate knowledge of abstract realities that transcend sensory experience.</p>" },
        { title: "Chapter 5: The Affinity Argument", text: "<p>Socrates distinguishes between two kinds of reality: the visible and the invisible. The body belongs to the visible realm — it is composite, changeable, and mortal. The soul belongs to the invisible realm — it is simple, unchanging, and divine.</p><p>Things that are composite can be broken apart and destroyed. Things that are simple and uniform cannot. Since the soul is more like the invisible, unchanging Forms than like the visible, changing body, it is likely to be indestructible.</p><p>Socrates adds that the soul rules the body, just as the divine rules the mortal. The soul's natural role is to command, which further suggests its kinship with the eternal and divine.</p>" },
        { title: "Chapter 6: Objections from Simmias and Cebes", text: "<p>Simmias raises a powerful objection. Perhaps the soul is like the harmony of a lyre. The harmony is invisible and beautiful, but when the lyre is destroyed, the harmony ceases to exist. Similarly, the soul might perish when the body dies.</p><p>Cebes offers a different objection. Perhaps the soul outlasts many bodies, like a weaver who outlasts many cloaks. But eventually the weaver dies. Perhaps the soul, too, eventually wears out after many incarnations.</p><p>These objections threaten to undermine everything Socrates has argued. The friends fall silent, worried that the case for immortality has been defeated. Socrates must find stronger arguments.</p>" },
        { title: "Chapter 7: Socrates Answers Simmias", text: "<p>Socrates responds to Simmias first. If the soul were merely a harmony, it could not have existed before the body — but they have already established through the Theory of Recollection that it did. A harmony cannot exist before the instrument that produces it.</p><p>Furthermore, a harmony cannot oppose the elements that compose it. But the soul regularly opposes the body's desires — resisting hunger, thirst, and fear. This shows the soul is not a mere byproduct of physical processes.</p><p>Socrates also notes that if the soul were a harmony, all souls would be equally harmonious, since all harmonies are equally harmonies. But we know that some souls are more virtuous than others. The harmony theory cannot account for moral differences.</p>" },
        { title: "Chapter 8: The Final Argument from Forms", text: "<p>Socrates presents his strongest argument. The soul is what brings life to the body. Life is the essential characteristic of the soul, just as heat is the essential characteristic of fire.</p><p>Fire can never admit cold — when cold approaches, fire either retreats or is extinguished. Similarly, the soul can never admit death. When death approaches, the soul must either retreat or cease to exist.</p><p>But we have already shown that the soul is simple and cannot be destroyed. Therefore, when death approaches, the soul retreats — it departs from the body and continues to exist elsewhere. The soul is immortal and indestructible.</p>" },
        { title: "Chapter 9: The Myth of the Afterlife", text: "<p>Socrates describes a myth about the fate of souls after death. The earth is far larger and more beautiful than we imagine. We live in a hollow on its surface, like creatures at the bottom of the sea who mistake their world for the whole.</p><p>After death, souls are judged. Those who lived virtuously are rewarded with beautiful dwelling places. Those who committed terrible crimes are cast into Tartarus. Most souls undergo purification before being reborn.</p><p>Socrates acknowledges that the details of this myth may not be exactly right. But he believes something like it must be true. The soul is immortal, and how we live matters for eternity. This belief gives the philosopher courage to face death.</p>" },
        { title: "Chapter 10: The Death of Socrates", text: "<p>The hour of execution arrives. Socrates bathes so that the women will not need to wash his body after death. He says goodbye to his children and the women of his family, then returns to his friends.</p><p>The jailer brings the cup of hemlock, weeping as he hands it over. He says Socrates is the noblest and gentlest man who has ever been in the prison. Socrates thanks him kindly and drinks the poison without hesitation.</p><p>His friends break down in tears. Socrates rebukes them gently — this is why he sent the women away. He walks around until his legs grow heavy, then lies down. The numbness spreads upward. His last words are: 'Crito, we owe a rooster to Asclepius. Pay it and do not neglect it.' Then he is gone. Phaedo concludes: 'Such was the end of our friend, the best, wisest, and most just of all the men of his time.'</p>" }
      ]
    }
  };

  var currentBook = null, currentPage = 0;

  function openBook(k) { currentBook = books[k]; if (!currentBook) return; currentPage = 0; document.getElementById("readerOverlay").classList.add("active"); document.body.style.overflow = "hidden"; renderPage(); }
  function closeBook() { document.getElementById("readerOverlay").classList.remove("active"); document.body.style.overflow = ""; currentBook = null; }
  function renderPage() {
    if (!currentBook) return;
    var ch = currentBook.chapters[currentPage], ci = document.getElementById("readerCoverImg"), ce = document.getElementById("readerChapter"), ti = document.getElementById("chapterTitle"), te = document.getElementById("chapterText"), ind = document.getElementById("readerIndicator"), rt = document.getElementById("readerTitle"), pb = document.getElementById("readerPrev"), nb = document.getElementById("readerNext");
    if (ch.type === "cover") { ci.style.display="block"; ci.src=currentBook.cover; ce.classList.remove("visible"); rt.textContent=currentBook.title; }
    else { ci.style.display="none"; ce.classList.add("visible"); ti.textContent=ch.title; te.innerHTML=ch.text; rt.textContent=ch.title; ce.scrollTop=0; }
    ind.textContent=(currentPage+1)+" / "+currentBook.chapters.length; pb.disabled=currentPage===0; nb.disabled=currentPage===currentBook.chapters.length-1;
  }

  document.querySelectorAll(".book-read-btn").forEach(function(b){b.addEventListener("click",function(){openBook(b.dataset.book);});});
  document.getElementById("readerBackBtn").addEventListener("click",closeBook);
  document.getElementById("readerPrev").addEventListener("click",function(){if(currentBook&&currentPage>0){currentPage--;renderPage();}});
  document.getElementById("readerNext").addEventListener("click",function(){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}});
  document.addEventListener("keydown",function(e){if(!document.getElementById("readerOverlay").classList.contains("active"))return;if(e.key==="ArrowRight"){if(currentBook&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}}else if(e.key==="ArrowLeft"){if(currentBook&&currentPage>0){currentPage--;renderPage();}}else if(e.key==="Escape"){closeBook();}});
  var scrollCD=false;document.getElementById("readerOverlay").addEventListener("wheel",function(e){if(!currentBook||scrollCD)return;var ce=document.getElementById("readerChapter");if(currentPage===0||!ce.classList.contains("visible")){e.preventDefault();scrollCD=true;if(e.deltaY>0&&currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}else if(e.deltaY<0&&currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);return;}var aT=ce.scrollTop<=0,aB=ce.scrollTop+ce.clientHeight>=ce.scrollHeight-5;if(aB&&e.deltaY>0){e.preventDefault();scrollCD=true;if(currentPage<currentBook.chapters.length-1){currentPage++;renderPage();}setTimeout(function(){scrollCD=false;},200);}else if(aT&&e.deltaY<0){e.preventDefault();scrollCD=true;if(currentPage>0){currentPage--;renderPage();}setTimeout(function(){scrollCD=false;},200);}},{passive:false});

  // ===================== 3D MODEL =====================
  var container = document.getElementById("modelContainer");
  var w = container.clientWidth, h = container.clientHeight;
  var scene = new THREE.Scene();
  var camera = new THREE.PerspectiveCamera(45, w/h, 0.01, 100);
  camera.position.set(0, 1, 3);
  var renderer = new THREE.WebGLRenderer({ antialias:true, alpha:true });
  renderer.setClearColor(0x000000, 0);
  renderer.setSize(w, h);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  container.appendChild(renderer.domElement);
  var controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enableDamping=true; controls.dampingFactor=0.05; controls.autoRotate=true; controls.autoRotateSpeed=2; controls.enableZoom=false; controls.target.set(0,0.8,0);
  scene.add(new THREE.AmbientLight(0xffffff,0.6));
  var dl=new THREE.DirectionalLight(0xffffff,1.5); dl.position.set(2,4,3); scene.add(dl);
  var fl=new THREE.DirectionalLight(0xffeedd,0.5); fl.position.set(-2,2,-1); scene.add(fl);
  scene.add(new THREE.HemisphereLight(0xffeeb1,0x080820,0.3));
  var loader=new THREE.GLTFLoader();
  loader.load("Assets/socrates.glb",function(g){var m=g.scene;var b=new THREE.Box3().setFromObject(m);var c=b.getCenter(new THREE.Vector3());var s=b.getSize(new THREE.Vector3());var mx=Math.max(s.x,s.y,s.z);var sc=2/mx;m.scale.setScalar(sc);m.position.sub(c.multiplyScalar(sc));m.position.y+=0.5;scene.add(m);controls.target.set(0,m.position.y+(s.y*sc)/2,0);},undefined,function(e){console.warn("Failed to load model:",e);});
  function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();
  window.addEventListener("resize",function(){var w2=container.clientWidth,h2=container.clientHeight;camera.aspect=w2/h2;camera.updateProjectionMatrix();renderer.setSize(w2,h2);});
})();
